// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokemons.API.Data;

namespace Pokemons.API.Migrations
{
    [DbContext(typeof(PokemonContext))]
    partial class PokemonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pokemons.API.Models.Pokemon", b =>
                {
                    b.Property<Guid>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("EggGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<int>("Hp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokedexEntry")
                        .HasColumnType("int");

                    b.Property<int>("SpAtk")
                        .HasColumnType("int");

                    b.Property<int>("SpDef")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.HasIndex("PokedexEntry", "Generation")
                        .IsUnique();

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            PokemonId = new Guid("e02cd172-022c-40d8-952d-3487b718c0e2"),
                            Attack = 110,
                            Classification = "Sleeping Pokemon",
                            Defense = 65,
                            EggGroup = "Monster",
                            Generation = 1,
                            Hp = 160,
                            Name = "Snorlax",
                            PokedexEntry = 143,
                            SpAtk = 65,
                            SpDef = 110,
                            Speed = 30
                        },
                        new
                        {
                            PokemonId = new Guid("8f66db89-d341-41f3-99f4-3f0c8d4312f6"),
                            Attack = 90,
                            Classification = "Blocking Pokemon",
                            Defense = 101,
                            EggGroup = "Field",
                            Generation = 8,
                            Hp = 93,
                            Name = "Obstagoon",
                            PokedexEntry = 598,
                            SpAtk = 60,
                            SpDef = 81,
                            Speed = 95
                        },
                        new
                        {
                            PokemonId = new Guid("51132596-3e9f-42bc-b919-3eb584e40fb7"),
                            Attack = 52,
                            Classification = "Lizard Pokemon",
                            Defense = 43,
                            EggGroup = "Monster,Dragon",
                            Generation = 1,
                            Hp = 39,
                            Name = "Charmander",
                            PokedexEntry = 4,
                            SpAtk = 60,
                            SpDef = 50,
                            Speed = 65
                        },
                        new
                        {
                            PokemonId = new Guid("491ee503-62ca-42fb-bc45-9556edbb4c4b"),
                            Attack = 60,
                            Classification = "Sun Pokemon",
                            Defense = 65,
                            EggGroup = "Bug",
                            Generation = 5,
                            Hp = 85,
                            Name = "Volcarona",
                            PokedexEntry = 637,
                            SpAtk = 135,
                            SpDef = 105,
                            Speed = 100
                        },
                        new
                        {
                            PokemonId = new Guid("02c1e3a9-d092-4ae8-9868-64fdb9583fd4"),
                            Attack = 100,
                            Classification = "Superpower Pokemon",
                            Defense = 70,
                            EggGroup = "Human-Like",
                            Generation = 1,
                            Hp = 80,
                            Name = "Machoke",
                            PokedexEntry = 67,
                            SpAtk = 50,
                            SpDef = 60,
                            Speed = 45
                        },
                        new
                        {
                            PokemonId = new Guid("a3e37508-fb8a-4787-a4a6-8f910b3f0489"),
                            Attack = 125,
                            Classification = "Single Horn Pokemon",
                            Defense = 75,
                            EggGroup = "Bug",
                            Generation = 2,
                            Hp = 80,
                            Name = "Heracross",
                            PokedexEntry = 214,
                            SpAtk = 40,
                            SpDef = 95,
                            Speed = 85
                        },
                        new
                        {
                            PokemonId = new Guid("ff118a41-b604-4cfe-8b9a-c0c10ba5e558"),
                            Attack = 110,
                            Classification = "Mud Fish Pokemon",
                            Defense = 90,
                            EggGroup = "Monster,Water 1",
                            Generation = 3,
                            Hp = 100,
                            Name = "Swampert",
                            PokedexEntry = 260,
                            SpAtk = 85,
                            SpDef = 90,
                            Speed = 60
                        },
                        new
                        {
                            PokemonId = new Guid("f9fe42b8-d15f-40f9-ab49-3de84c64f2ae"),
                            Attack = 60,
                            Classification = "Mock Kelp Pokemon",
                            Defense = 60,
                            EggGroup = "Bug",
                            Generation = 6,
                            Hp = 50,
                            Name = "Skrelp",
                            PokedexEntry = 637,
                            SpAtk = 60,
                            SpDef = 60,
                            Speed = 30
                        },
                        new
                        {
                            PokemonId = new Guid("5d5df3b1-f0dd-4b66-8a19-c53f89313dd3"),
                            Attack = 87,
                            Classification = "Raven Pokemon",
                            Defense = 105,
                            EggGroup = "Flying",
                            Generation = 8,
                            Hp = 98,
                            Name = "Corviknight",
                            PokedexEntry = 823,
                            SpAtk = 53,
                            SpDef = 85,
                            Speed = 67
                        },
                        new
                        {
                            PokemonId = new Guid("239aa97e-7e2a-41e8-9f6c-00a8a33458d3"),
                            Attack = 50,
                            Classification = "Balloon Pokemon",
                            Defense = 34,
                            EggGroup = "Amorphous",
                            Generation = 4,
                            Hp = 90,
                            Name = "Drifloon",
                            PokedexEntry = 425,
                            SpAtk = 60,
                            SpDef = 44,
                            Speed = 70
                        },
                        new
                        {
                            PokemonId = new Guid("0f3cf491-a4dd-4558-a9d9-256bdc4168ab"),
                            Attack = 55,
                            Classification = "Sickle Grass Pokemon",
                            Defense = 35,
                            EggGroup = "Grass",
                            Generation = 7,
                            Hp = 40,
                            Name = "Fomantis",
                            PokedexEntry = 753,
                            SpAtk = 50,
                            SpDef = 35,
                            Speed = 35
                        },
                        new
                        {
                            PokemonId = new Guid("90aa96ad-5ad4-45c5-8047-caedbc9d1547"),
                            Attack = 41,
                            Classification = "Sea Lily Pokemon",
                            Defense = 77,
                            EggGroup = "Water 3",
                            Generation = 3,
                            Hp = 66,
                            Name = "Lileep",
                            PokedexEntry = 345,
                            SpAtk = 61,
                            SpDef = 87,
                            Speed = 23
                        },
                        new
                        {
                            PokemonId = new Guid("7489545c-9f12-4872-912f-b9e7174ed68c"),
                            Attack = 73,
                            Classification = "Poison Pin Pokemon",
                            Defense = 73,
                            EggGroup = "Undiscovered",
                            Generation = 7,
                            Hp = 73,
                            Name = "Naganadel",
                            PokedexEntry = 804,
                            SpAtk = 127,
                            SpDef = 73,
                            Speed = 121
                        },
                        new
                        {
                            PokemonId = new Guid("72015dbc-2ec8-431d-a343-38396f6c401c"),
                            Attack = 70,
                            Classification = "Bouquet Pokemon",
                            Defense = 55,
                            EggGroup = "Fairy,Grass",
                            Generation = 4,
                            Hp = 60,
                            Name = "Roserade",
                            PokedexEntry = 407,
                            SpAtk = 125,
                            SpDef = 105,
                            Speed = 90
                        },
                        new
                        {
                            PokemonId = new Guid("0a60a384-55c5-4639-8d93-1bcd036533b9"),
                            Attack = 70,
                            Classification = "Magnet Area Pokemon",
                            Defense = 115,
                            EggGroup = "Mineral",
                            Generation = 4,
                            Hp = 70,
                            Name = "Magnezone",
                            PokedexEntry = 462,
                            SpAtk = 130,
                            SpDef = 90,
                            Speed = 60
                        },
                        new
                        {
                            PokemonId = new Guid("1c9805f8-4eef-46b8-b3f2-681a686b912a"),
                            Attack = 150,
                            Classification = "Deep Black Pokemon",
                            Defense = 120,
                            EggGroup = "Undiscovered",
                            Generation = 5,
                            Hp = 100,
                            Name = "Zekrom",
                            PokedexEntry = 644,
                            SpAtk = 120,
                            SpDef = 100,
                            Speed = 90
                        },
                        new
                        {
                            PokemonId = new Guid("98346c71-606f-4ce0-b53b-867e467cdfaf"),
                            Attack = 74,
                            Classification = "Automaton Pokemon",
                            Defense = 50,
                            EggGroup = "Mineral",
                            Generation = 5,
                            Hp = 59,
                            Name = "Golett",
                            PokedexEntry = 622,
                            SpAtk = 35,
                            SpDef = 50,
                            Speed = 35
                        },
                        new
                        {
                            PokemonId = new Guid("38d734cb-008f-4b79-9185-6c076dc176e2"),
                            Attack = 100,
                            Classification = "Order Pokemon",
                            Defense = 121,
                            EggGroup = "Undiscovered",
                            Generation = 6,
                            Hp = 216,
                            Name = "Zygarde",
                            PokedexEntry = 718,
                            SpAtk = 91,
                            SpDef = 95,
                            Speed = 85
                        },
                        new
                        {
                            PokemonId = new Guid("d233f762-7b17-4374-83a6-c08c957de765"),
                            Attack = 20,
                            Classification = "Psi Pokemon",
                            Defense = 15,
                            EggGroup = "Human-Like",
                            Generation = 1,
                            Hp = 25,
                            Name = "Abra",
                            PokedexEntry = 63,
                            SpAtk = 105,
                            SpDef = 55,
                            Speed = 90
                        },
                        new
                        {
                            PokemonId = new Guid("24c2d5fd-1fe8-4b1c-8cc6-5dac519e7f41"),
                            Attack = 89,
                            Classification = "Bronze Bell Pokemon",
                            Defense = 116,
                            EggGroup = "Mineral",
                            Generation = 4,
                            Hp = 67,
                            Name = "Bronzong",
                            PokedexEntry = 437,
                            SpAtk = 79,
                            SpDef = 116,
                            Speed = 33
                        },
                        new
                        {
                            PokemonId = new Guid("04f8c30a-daf5-431a-8819-11b926e807c1"),
                            Attack = 165,
                            Classification = "Head Butt Pokemon",
                            Defense = 60,
                            EggGroup = "Monster",
                            Generation = 4,
                            Hp = 97,
                            Name = "Rampardos",
                            PokedexEntry = 409,
                            SpAtk = 65,
                            SpDef = 50,
                            Speed = 58
                        },
                        new
                        {
                            PokemonId = new Guid("a72ac717-a8bb-47e4-afd8-d5a3e2766881"),
                            Attack = 77,
                            Classification = "Tundra Pokemon",
                            Defense = 72,
                            EggGroup = "Monster",
                            Generation = 6,
                            Hp = 123,
                            Name = "Aurorus",
                            PokedexEntry = 699,
                            SpAtk = 99,
                            SpDef = 92,
                            Speed = 58
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.PokemonTyping", b =>
                {
                    b.Property<Guid>("PokemonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypingId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "TypingId");

                    b.HasIndex("TypingId");

                    b.ToTable("PokemonTyping");

                    b.HasData(
                        new
                        {
                            PokemonId = new Guid("e02cd172-022c-40d8-952d-3487b718c0e2"),
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = new Guid("8f66db89-d341-41f3-99f4-3f0c8d4312f6"),
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = new Guid("8f66db89-d341-41f3-99f4-3f0c8d4312f6"),
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = new Guid("51132596-3e9f-42bc-b919-3eb584e40fb7"),
                            TypingId = 2
                        },
                        new
                        {
                            PokemonId = new Guid("491ee503-62ca-42fb-bc45-9556edbb4c4b"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("491ee503-62ca-42fb-bc45-9556edbb4c4b"),
                            TypingId = 2
                        },
                        new
                        {
                            PokemonId = new Guid("02c1e3a9-d092-4ae8-9868-64fdb9583fd4"),
                            TypingId = 3
                        },
                        new
                        {
                            PokemonId = new Guid("a3e37508-fb8a-4787-a4a6-8f910b3f0489"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("a3e37508-fb8a-4787-a4a6-8f910b3f0489"),
                            TypingId = 3
                        },
                        new
                        {
                            PokemonId = new Guid("ff118a41-b604-4cfe-8b9a-c0c10ba5e558"),
                            TypingId = 4
                        },
                        new
                        {
                            PokemonId = new Guid("ff118a41-b604-4cfe-8b9a-c0c10ba5e558"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("f9fe42b8-d15f-40f9-ab49-3de84c64f2ae"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("f9fe42b8-d15f-40f9-ab49-3de84c64f2ae"),
                            TypingId = 4
                        },
                        new
                        {
                            PokemonId = new Guid("5d5df3b1-f0dd-4b66-8a19-c53f89313dd3"),
                            TypingId = 5
                        },
                        new
                        {
                            PokemonId = new Guid("5d5df3b1-f0dd-4b66-8a19-c53f89313dd3"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("239aa97e-7e2a-41e8-9f6c-00a8a33458d3"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("239aa97e-7e2a-41e8-9f6c-00a8a33458d3"),
                            TypingId = 5
                        },
                        new
                        {
                            PokemonId = new Guid("0f3cf491-a4dd-4558-a9d9-256bdc4168ab"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("90aa96ad-5ad4-45c5-8047-caedbc9d1547"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("90aa96ad-5ad4-45c5-8047-caedbc9d1547"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("7489545c-9f12-4872-912f-b9e7174ed68c"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("7489545c-9f12-4872-912f-b9e7174ed68c"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("72015dbc-2ec8-431d-a343-38396f6c401c"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("72015dbc-2ec8-431d-a343-38396f6c401c"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("0a60a384-55c5-4639-8d93-1bcd036533b9"),
                            TypingId = 8
                        },
                        new
                        {
                            PokemonId = new Guid("0a60a384-55c5-4639-8d93-1bcd036533b9"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("1c9805f8-4eef-46b8-b3f2-681a686b912a"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("1c9805f8-4eef-46b8-b3f2-681a686b912a"),
                            TypingId = 8
                        },
                        new
                        {
                            PokemonId = new Guid("98346c71-606f-4ce0-b53b-867e467cdfaf"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("98346c71-606f-4ce0-b53b-867e467cdfaf"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("38d734cb-008f-4b79-9185-6c076dc176e2"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("38d734cb-008f-4b79-9185-6c076dc176e2"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("d233f762-7b17-4374-83a6-c08c957de765"),
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = new Guid("24c2d5fd-1fe8-4b1c-8cc6-5dac519e7f41"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("24c2d5fd-1fe8-4b1c-8cc6-5dac519e7f41"),
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = new Guid("04f8c30a-daf5-431a-8819-11b926e807c1"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("a72ac717-a8bb-47e4-afd8-d5a3e2766881"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("a72ac717-a8bb-47e4-afd8-d5a3e2766881"),
                            TypingId = 12
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.TypeEffect", b =>
                {
                    b.Property<int>("TypeEffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DefenseTypingId")
                        .HasColumnType("int");

                    b.Property<int>("OffenseTypingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TypeEffectId");

                    b.HasIndex("DefenseTypingId");

                    b.HasIndex("OffenseTypingId");

                    b.ToTable("TypeEffects");

                    b.HasData(
                        new
                        {
                            TypeEffectId = 1,
                            DefenseTypingId = 11,
                            OffenseTypingId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 2,
                            DefenseTypingId = 17,
                            OffenseTypingId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 3,
                            DefenseTypingId = 15,
                            OffenseTypingId = 1,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 4,
                            DefenseTypingId = 13,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 5,
                            DefenseTypingId = 6,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 6,
                            DefenseTypingId = 12,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 7,
                            DefenseTypingId = 14,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 8,
                            DefenseTypingId = 2,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 9,
                            DefenseTypingId = 11,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 10,
                            DefenseTypingId = 4,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 11,
                            DefenseTypingId = 16,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 12,
                            DefenseTypingId = 12,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 13,
                            DefenseTypingId = 1,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 14,
                            DefenseTypingId = 11,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 15,
                            DefenseTypingId = 17,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 16,
                            DefenseTypingId = 13,
                            OffenseTypingId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 17,
                            DefenseTypingId = 18,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 18,
                            DefenseTypingId = 5,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 19,
                            DefenseTypingId = 7,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 20,
                            DefenseTypingId = 10,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 21,
                            DefenseTypingId = 15,
                            OffenseTypingId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 22,
                            DefenseTypingId = 2,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 23,
                            DefenseTypingId = 9,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 24,
                            DefenseTypingId = 11,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 25,
                            DefenseTypingId = 14,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 26,
                            DefenseTypingId = 6,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 27,
                            DefenseTypingId = 4,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 28,
                            DefenseTypingId = 13,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 29,
                            DefenseTypingId = 3,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 30,
                            DefenseTypingId = 6,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 31,
                            DefenseTypingId = 8,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 32,
                            DefenseTypingId = 11,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 33,
                            DefenseTypingId = 17,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 34,
                            DefenseTypingId = 9,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 35,
                            DefenseTypingId = 11,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 36,
                            DefenseTypingId = 4,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 37,
                            DefenseTypingId = 13,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 38,
                            DefenseTypingId = 14,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 39,
                            DefenseTypingId = 2,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 40,
                            DefenseTypingId = 5,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 41,
                            DefenseTypingId = 6,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 42,
                            DefenseTypingId = 7,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 43,
                            DefenseTypingId = 17,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 44,
                            DefenseTypingId = 18,
                            OffenseTypingId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 45,
                            DefenseTypingId = 6,
                            OffenseTypingId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 46,
                            DefenseTypingId = 7,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 47,
                            DefenseTypingId = 9,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 48,
                            DefenseTypingId = 11,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 49,
                            DefenseTypingId = 15,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 50,
                            DefenseTypingId = 5,
                            OffenseTypingId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 51,
                            DefenseTypingId = 4,
                            OffenseTypingId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 52,
                            DefenseTypingId = 14,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 53,
                            DefenseTypingId = 8,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 54,
                            DefenseTypingId = 6,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 55,
                            DefenseTypingId = 9,
                            OffenseTypingId = 8,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 56,
                            DefenseTypingId = 8,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 57,
                            DefenseTypingId = 2,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 58,
                            DefenseTypingId = 7,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 59,
                            DefenseTypingId = 11,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 60,
                            DefenseTypingId = 17,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 61,
                            DefenseTypingId = 13,
                            OffenseTypingId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 62,
                            DefenseTypingId = 6,
                            OffenseTypingId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 63,
                            DefenseTypingId = 5,
                            OffenseTypingId = 9,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 64,
                            DefenseTypingId = 7,
                            OffenseTypingId = 10,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 65,
                            DefenseTypingId = 10,
                            OffenseTypingId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 66,
                            DefenseTypingId = 17,
                            OffenseTypingId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 67,
                            DefenseTypingId = 16,
                            OffenseTypingId = 10,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 68,
                            DefenseTypingId = 13,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 69,
                            DefenseTypingId = 2,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 70,
                            DefenseTypingId = 5,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 71,
                            DefenseTypingId = 12,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 72,
                            DefenseTypingId = 3,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 73,
                            DefenseTypingId = 9,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 74,
                            DefenseTypingId = 17,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 75,
                            DefenseTypingId = 14,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 76,
                            DefenseTypingId = 5,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 77,
                            DefenseTypingId = 6,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 78,
                            DefenseTypingId = 9,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 79,
                            DefenseTypingId = 2,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 80,
                            DefenseTypingId = 12,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 81,
                            DefenseTypingId = 17,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 82,
                            DefenseTypingId = 4,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 83,
                            DefenseTypingId = 16,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 84,
                            DefenseTypingId = 6,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 85,
                            DefenseTypingId = 10,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 86,
                            DefenseTypingId = 18,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 87,
                            DefenseTypingId = 3,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 88,
                            DefenseTypingId = 2,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 89,
                            DefenseTypingId = 5,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 90,
                            DefenseTypingId = 15,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 91,
                            DefenseTypingId = 7,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 92,
                            DefenseTypingId = 17,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 93,
                            DefenseTypingId = 14,
                            OffenseTypingId = 14,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 94,
                            DefenseTypingId = 17,
                            OffenseTypingId = 14,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 95,
                            DefenseTypingId = 18,
                            OffenseTypingId = 14,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 96,
                            DefenseTypingId = 15,
                            OffenseTypingId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 97,
                            DefenseTypingId = 10,
                            OffenseTypingId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 98,
                            DefenseTypingId = 16,
                            OffenseTypingId = 15,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 99,
                            DefenseTypingId = 1,
                            OffenseTypingId = 15,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 100,
                            DefenseTypingId = 15,
                            OffenseTypingId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 101,
                            DefenseTypingId = 10,
                            OffenseTypingId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 102,
                            DefenseTypingId = 16,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 103,
                            DefenseTypingId = 18,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 104,
                            DefenseTypingId = 3,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 105,
                            DefenseTypingId = 18,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 106,
                            DefenseTypingId = 12,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 107,
                            DefenseTypingId = 11,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 108,
                            DefenseTypingId = 8,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 109,
                            DefenseTypingId = 2,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 110,
                            DefenseTypingId = 17,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 111,
                            DefenseTypingId = 4,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 112,
                            DefenseTypingId = 16,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 113,
                            DefenseTypingId = 14,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 114,
                            DefenseTypingId = 3,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 115,
                            DefenseTypingId = 2,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 116,
                            DefenseTypingId = 7,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 117,
                            DefenseTypingId = 17,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.Typing", b =>
                {
                    b.Property<int>("TypingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypingId");

                    b.ToTable("Typings");

                    b.HasData(
                        new
                        {
                            TypingId = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            TypingId = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            TypingId = 3,
                            Name = "Fighting"
                        },
                        new
                        {
                            TypingId = 4,
                            Name = "Water"
                        },
                        new
                        {
                            TypingId = 5,
                            Name = "Flying"
                        },
                        new
                        {
                            TypingId = 6,
                            Name = "Grass"
                        },
                        new
                        {
                            TypingId = 7,
                            Name = "Poison"
                        },
                        new
                        {
                            TypingId = 8,
                            Name = "Electric"
                        },
                        new
                        {
                            TypingId = 9,
                            Name = "Ground"
                        },
                        new
                        {
                            TypingId = 10,
                            Name = "Psychic"
                        },
                        new
                        {
                            TypingId = 11,
                            Name = "Rock"
                        },
                        new
                        {
                            TypingId = 12,
                            Name = "Ice"
                        },
                        new
                        {
                            TypingId = 13,
                            Name = "Bug"
                        },
                        new
                        {
                            TypingId = 14,
                            Name = "Dragon"
                        },
                        new
                        {
                            TypingId = 15,
                            Name = "Ghost"
                        },
                        new
                        {
                            TypingId = 16,
                            Name = "Dark"
                        },
                        new
                        {
                            TypingId = 17,
                            Name = "Steel"
                        },
                        new
                        {
                            TypingId = 18,
                            Name = "Fairy"
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.PokemonTyping", b =>
                {
                    b.HasOne("Pokemons.API.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonTypings")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pokemons.API.Models.Typing", "Typing")
                        .WithMany("PokemonTypings")
                        .HasForeignKey("TypingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Typing");
                });

            modelBuilder.Entity("Pokemons.API.Models.TypeEffect", b =>
                {
                    b.HasOne("Pokemons.API.Models.Typing", "DefenseTyping")
                        .WithMany("TypeDefense")
                        .HasForeignKey("DefenseTypingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pokemons.API.Models.Typing", "OffenseTyping")
                        .WithMany("TypeOffense")
                        .HasForeignKey("OffenseTypingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DefenseTyping");

                    b.Navigation("OffenseTyping");
                });

            modelBuilder.Entity("Pokemons.API.Models.Pokemon", b =>
                {
                    b.Navigation("PokemonTypings");
                });

            modelBuilder.Entity("Pokemons.API.Models.Typing", b =>
                {
                    b.Navigation("PokemonTypings");

                    b.Navigation("TypeDefense");

                    b.Navigation("TypeOffense");
                });
#pragma warning restore 612, 618
        }
    }
}
