// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokemons.API.Data;

namespace Pokemons.API.Migrations
{
    [DbContext(typeof(PokemonContext))]
    partial class PokemonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pokemons.API.Models.Pokemon", b =>
                {
                    b.Property<Guid>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EggGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokedexEntry")
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.HasIndex("PokedexEntry", "Generation")
                        .IsUnique();

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            PokemonId = new Guid("762d45e1-f559-4338-aa51-e781962fcb2d"),
                            Classification = "Sleeping Pokemon",
                            EggGroup = "Monster",
                            Generation = 1,
                            Name = "Snorlax",
                            PokedexEntry = 143
                        },
                        new
                        {
                            PokemonId = new Guid("e86662c3-077f-4f88-abf6-a158ec1cc858"),
                            Classification = "Blocking Pokemon",
                            EggGroup = "Field",
                            Generation = 8,
                            Name = "Obstagoon",
                            PokedexEntry = 598
                        },
                        new
                        {
                            PokemonId = new Guid("59682e49-8da3-4fa6-9bc3-4b04094af87a"),
                            Classification = "Lizard Pokemon",
                            EggGroup = "Monster,Dragon",
                            Generation = 1,
                            Name = "Charmander",
                            PokedexEntry = 4
                        },
                        new
                        {
                            PokemonId = new Guid("03a715fe-0cda-40ce-9b81-c8256e99b5af"),
                            Classification = "Sun Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Volcarona",
                            PokedexEntry = 637
                        },
                        new
                        {
                            PokemonId = new Guid("de51da3f-4d12-463d-8b33-fe23d00c9487"),
                            Classification = "Superpower Pokemon",
                            EggGroup = "Human-Like",
                            Generation = 1,
                            Name = "Machoke",
                            PokedexEntry = 67
                        },
                        new
                        {
                            PokemonId = new Guid("812daf11-fa93-41bc-8024-006f216e1ca9"),
                            Classification = "Single Horn Pokemon",
                            EggGroup = "Bug",
                            Generation = 2,
                            Name = "Heracross",
                            PokedexEntry = 214
                        },
                        new
                        {
                            PokemonId = new Guid("9cd88407-247f-40ee-9e7d-10056bad9f4e"),
                            Classification = "Mud Fish Pokemon",
                            EggGroup = "Monster,Water 1",
                            Generation = 3,
                            Name = "Swampert",
                            PokedexEntry = 260
                        },
                        new
                        {
                            PokemonId = new Guid("2cccd836-5e6f-408b-9198-70f215c12c13"),
                            Classification = "Mock Kelp Pokemon",
                            EggGroup = "Bug",
                            Generation = 6,
                            Name = "Skrelp",
                            PokedexEntry = 637
                        },
                        new
                        {
                            PokemonId = new Guid("931653af-88ec-45e1-9f4d-05f8e0401963"),
                            Classification = "Raven Pokemon",
                            EggGroup = "Flying",
                            Generation = 8,
                            Name = "Corviknight",
                            PokedexEntry = 823
                        },
                        new
                        {
                            PokemonId = new Guid("0c693784-c08b-44d0-ba30-1fa43784e085"),
                            Classification = "Balloon Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 4,
                            Name = "Drifloon",
                            PokedexEntry = 425
                        },
                        new
                        {
                            PokemonId = new Guid("b641379b-d93e-4873-aeea-1cdce12985bf"),
                            Classification = "Sickle Grass Pokemon",
                            EggGroup = "Grass",
                            Generation = 7,
                            Name = "Fomantis",
                            PokedexEntry = 753
                        },
                        new
                        {
                            PokemonId = new Guid("61e046ab-e29b-4f9f-a766-c95f558639c2"),
                            Classification = "Sea Lily Pokemon",
                            EggGroup = "Water 3",
                            Generation = 3,
                            Name = "Lileep",
                            PokedexEntry = 345
                        },
                        new
                        {
                            PokemonId = new Guid("31a78165-3172-486e-a878-16a682b952f8"),
                            Classification = "Poison Pin Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 7,
                            Name = "Naganadel",
                            PokedexEntry = 804
                        },
                        new
                        {
                            PokemonId = new Guid("e66152de-35f0-4ba8-8b2f-75d17f68c515"),
                            Classification = "Bouquet Pokemon",
                            EggGroup = "Fairy,Grass",
                            Generation = 4,
                            Name = "Roserade",
                            PokedexEntry = 407
                        },
                        new
                        {
                            PokemonId = new Guid("94378bee-6bab-4bf0-91a1-3a650b35f55f"),
                            Classification = "Magnet Area Pokemon",
                            EggGroup = "Mineral",
                            Generation = 4,
                            Name = "Magnezone",
                            PokedexEntry = 462
                        },
                        new
                        {
                            PokemonId = new Guid("debc1386-2792-4b0c-8abe-f40ab2b91370"),
                            Classification = "Deep Black Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 5,
                            Name = "Zekrom",
                            PokedexEntry = 644
                        },
                        new
                        {
                            PokemonId = new Guid("85ecf0f7-4aed-49bd-9a84-836b023eab11"),
                            Classification = "Automaton Pokemon",
                            EggGroup = "Mineral",
                            Generation = 5,
                            Name = "Golett",
                            PokedexEntry = 622
                        },
                        new
                        {
                            PokemonId = new Guid("2c52fd70-7e8b-4b33-b25d-48cfa0546ed4"),
                            Classification = "Order Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 6,
                            Name = "Zygarde",
                            PokedexEntry = 718
                        },
                        new
                        {
                            PokemonId = new Guid("84efed31-01e8-4ac4-896e-6abb8d073e09"),
                            Classification = "Psi Pokemon",
                            EggGroup = "Human-Like",
                            Generation = 1,
                            Name = "Abra",
                            PokedexEntry = 63
                        },
                        new
                        {
                            PokemonId = new Guid("1000b9b8-0ab4-4c98-8138-9b15a202ac7b"),
                            Classification = "Bronze Bell Pokemon",
                            EggGroup = "Mineral",
                            Generation = 4,
                            Name = "Bronzong",
                            PokedexEntry = 437
                        },
                        new
                        {
                            PokemonId = new Guid("6a2c07aa-7261-4d3c-9ba0-77cdf2a1d4fe"),
                            Classification = "Head Butt Pokemon",
                            EggGroup = "Monster",
                            Generation = 4,
                            Name = "Rampardos",
                            PokedexEntry = 409
                        },
                        new
                        {
                            PokemonId = new Guid("94a79ddc-e37b-48ca-ac34-8c4038880a52"),
                            Classification = "Tundra Pokemon",
                            EggGroup = "Monster",
                            Generation = 6,
                            Name = "Aurorus",
                            PokedexEntry = 699
                        },
                        new
                        {
                            PokemonId = new Guid("6c83e537-25ea-49f0-ba14-9b50e9000c7b"),
                            Classification = "Snow Hat Pokemon",
                            EggGroup = "Fairy,Mineral",
                            Generation = 3,
                            Name = "Snorunt",
                            PokedexEntry = 361
                        },
                        new
                        {
                            PokemonId = new Guid("897df779-b730-4a4d-b841-2ed62f40c1ff"),
                            Classification = "Worm Pokemon",
                            EggGroup = "Bug",
                            Generation = 8,
                            Name = "Snom",
                            PokedexEntry = 872
                        },
                        new
                        {
                            PokemonId = new Guid("21fc93e2-4d82-4fdc-9ebe-6668ae978d91"),
                            Classification = "Leaf-Wrapped Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Swadloon",
                            PokedexEntry = 541
                        },
                        new
                        {
                            PokemonId = new Guid("ac0145d3-8ee5-4568-b2bb-408d58a5c122"),
                            Classification = "Curlipede Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Whirlipede",
                            PokedexEntry = 544
                        },
                        new
                        {
                            PokemonId = new Guid("870ba31b-e824-485f-9708-4077b2fcd469"),
                            Classification = "Dragon Pokemon",
                            EggGroup = "Water 1,Dragon",
                            Generation = 1,
                            Name = "Dragonair",
                            PokedexEntry = 148
                        },
                        new
                        {
                            PokemonId = new Guid("08f79218-253b-4b66-9598-1b59daa2276d"),
                            Classification = "Stealth Pokemon",
                            EggGroup = "Amorphous,Dragon",
                            Generation = 8,
                            Name = "Dragapult",
                            PokedexEntry = 887
                        },
                        new
                        {
                            PokemonId = new Guid("221a1deb-a7b7-4cb2-a3cf-99452981dfc8"),
                            Classification = "Screech Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 2,
                            Name = "Misdreavus",
                            PokedexEntry = 200
                        },
                        new
                        {
                            PokemonId = new Guid("41b97bfb-0aa2-427b-abbe-a29ead3ca5d6"),
                            Classification = "Magical Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 4,
                            Name = "Mismagius",
                            PokedexEntry = 429
                        },
                        new
                        {
                            PokemonId = new Guid("28d4f7de-c007-478c-9966-f40de0e7c1fb"),
                            Classification = "Wily Pokemon",
                            EggGroup = "Field,Grass",
                            Generation = 3,
                            Name = "Nuzleaf",
                            PokedexEntry = 274
                        },
                        new
                        {
                            PokemonId = new Guid("88089c96-d087-42dd-81a0-8df45a22f62c"),
                            Classification = "Skunk Pokemon",
                            EggGroup = "Field",
                            Generation = 4,
                            Name = "Skuntank",
                            PokedexEntry = 435
                        },
                        new
                        {
                            PokemonId = new Guid("8c9f3551-07e9-45a4-9309-f980531ae37b"),
                            Classification = "Iron Armor Pokemon",
                            EggGroup = "Monster",
                            Generation = 3,
                            Name = "Aggron",
                            PokedexEntry = 306
                        },
                        new
                        {
                            PokemonId = new Guid("78d31781-65a8-424e-95ab-7c90368b7d2b"),
                            Classification = "Thorn Pod Pokemon",
                            EggGroup = "Grass,Mineral",
                            Generation = 5,
                            Name = "Ferrothorn",
                            PokedexEntry = 598
                        },
                        new
                        {
                            PokemonId = new Guid("a95e9062-e194-4abd-8dfe-83991aacfb54"),
                            Classification = "Balloon Pokemon",
                            EggGroup = "Fairy",
                            Generation = 1,
                            Name = "Jigglypuff",
                            PokedexEntry = 39
                        },
                        new
                        {
                            PokemonId = new Guid("d9f537f2-7042-4fd5-a9f4-d6de1b47a4fe"),
                            Classification = "Embrace Pokemon",
                            EggGroup = "Human-Like,Amorphous",
                            Generation = 3,
                            Name = "Gardevoir",
                            PokedexEntry = 282
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.PokemonTyping", b =>
                {
                    b.Property<Guid>("PokemonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypingId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "TypingId");

                    b.HasIndex("TypingId");

                    b.ToTable("PokemonTyping");

                    b.HasData(
                        new
                        {
                            PokemonId = new Guid("762d45e1-f559-4338-aa51-e781962fcb2d"),
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = new Guid("e86662c3-077f-4f88-abf6-a158ec1cc858"),
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = new Guid("e86662c3-077f-4f88-abf6-a158ec1cc858"),
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = new Guid("59682e49-8da3-4fa6-9bc3-4b04094af87a"),
                            TypingId = 2
                        },
                        new
                        {
                            PokemonId = new Guid("03a715fe-0cda-40ce-9b81-c8256e99b5af"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("03a715fe-0cda-40ce-9b81-c8256e99b5af"),
                            TypingId = 2
                        },
                        new
                        {
                            PokemonId = new Guid("de51da3f-4d12-463d-8b33-fe23d00c9487"),
                            TypingId = 3
                        },
                        new
                        {
                            PokemonId = new Guid("812daf11-fa93-41bc-8024-006f216e1ca9"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("812daf11-fa93-41bc-8024-006f216e1ca9"),
                            TypingId = 3
                        },
                        new
                        {
                            PokemonId = new Guid("9cd88407-247f-40ee-9e7d-10056bad9f4e"),
                            TypingId = 4
                        },
                        new
                        {
                            PokemonId = new Guid("9cd88407-247f-40ee-9e7d-10056bad9f4e"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("2cccd836-5e6f-408b-9198-70f215c12c13"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("2cccd836-5e6f-408b-9198-70f215c12c13"),
                            TypingId = 4
                        },
                        new
                        {
                            PokemonId = new Guid("931653af-88ec-45e1-9f4d-05f8e0401963"),
                            TypingId = 5
                        },
                        new
                        {
                            PokemonId = new Guid("931653af-88ec-45e1-9f4d-05f8e0401963"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("0c693784-c08b-44d0-ba30-1fa43784e085"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("0c693784-c08b-44d0-ba30-1fa43784e085"),
                            TypingId = 5
                        },
                        new
                        {
                            PokemonId = new Guid("b641379b-d93e-4873-aeea-1cdce12985bf"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("61e046ab-e29b-4f9f-a766-c95f558639c2"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("61e046ab-e29b-4f9f-a766-c95f558639c2"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("31a78165-3172-486e-a878-16a682b952f8"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("31a78165-3172-486e-a878-16a682b952f8"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("e66152de-35f0-4ba8-8b2f-75d17f68c515"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("e66152de-35f0-4ba8-8b2f-75d17f68c515"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("94378bee-6bab-4bf0-91a1-3a650b35f55f"),
                            TypingId = 8
                        },
                        new
                        {
                            PokemonId = new Guid("94378bee-6bab-4bf0-91a1-3a650b35f55f"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("debc1386-2792-4b0c-8abe-f40ab2b91370"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("debc1386-2792-4b0c-8abe-f40ab2b91370"),
                            TypingId = 8
                        },
                        new
                        {
                            PokemonId = new Guid("85ecf0f7-4aed-49bd-9a84-836b023eab11"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("85ecf0f7-4aed-49bd-9a84-836b023eab11"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("2c52fd70-7e8b-4b33-b25d-48cfa0546ed4"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("2c52fd70-7e8b-4b33-b25d-48cfa0546ed4"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("84efed31-01e8-4ac4-896e-6abb8d073e09"),
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = new Guid("1000b9b8-0ab4-4c98-8138-9b15a202ac7b"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("1000b9b8-0ab4-4c98-8138-9b15a202ac7b"),
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = new Guid("6a2c07aa-7261-4d3c-9ba0-77cdf2a1d4fe"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("94a79ddc-e37b-48ca-ac34-8c4038880a52"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("94a79ddc-e37b-48ca-ac34-8c4038880a52"),
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = new Guid("6c83e537-25ea-49f0-ba14-9b50e9000c7b"),
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = new Guid("897df779-b730-4a4d-b841-2ed62f40c1ff"),
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = new Guid("897df779-b730-4a4d-b841-2ed62f40c1ff"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("21fc93e2-4d82-4fdc-9ebe-6668ae978d91"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("21fc93e2-4d82-4fdc-9ebe-6668ae978d91"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("ac0145d3-8ee5-4568-b2bb-408d58a5c122"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("ac0145d3-8ee5-4568-b2bb-408d58a5c122"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("870ba31b-e824-485f-9708-4077b2fcd469"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("08f79218-253b-4b66-9598-1b59daa2276d"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("08f79218-253b-4b66-9598-1b59daa2276d"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("221a1deb-a7b7-4cb2-a3cf-99452981dfc8"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("41b97bfb-0aa2-427b-abbe-a29ead3ca5d6"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("28d4f7de-c007-478c-9966-f40de0e7c1fb"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("28d4f7de-c007-478c-9966-f40de0e7c1fb"),
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = new Guid("88089c96-d087-42dd-81a0-8df45a22f62c"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("88089c96-d087-42dd-81a0-8df45a22f62c"),
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = new Guid("8c9f3551-07e9-45a4-9309-f980531ae37b"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("8c9f3551-07e9-45a4-9309-f980531ae37b"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("78d31781-65a8-424e-95ab-7c90368b7d2b"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("78d31781-65a8-424e-95ab-7c90368b7d2b"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("a95e9062-e194-4abd-8dfe-83991aacfb54"),
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = new Guid("a95e9062-e194-4abd-8dfe-83991aacfb54"),
                            TypingId = 18
                        },
                        new
                        {
                            PokemonId = new Guid("d9f537f2-7042-4fd5-a9f4-d6de1b47a4fe"),
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = new Guid("d9f537f2-7042-4fd5-a9f4-d6de1b47a4fe"),
                            TypingId = 18
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.TypeEffect", b =>
                {
                    b.Property<int>("TypeEffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DefenseTypingId")
                        .HasColumnType("int");

                    b.Property<int>("OffenseTypingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TypeEffectId");

                    b.HasIndex("DefenseTypingId");

                    b.HasIndex("OffenseTypingId");

                    b.ToTable("TypeEffects");

                    b.HasData(
                        new
                        {
                            TypeEffectId = 1,
                            DefenseTypingId = 11,
                            OffenseTypingId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 2,
                            DefenseTypingId = 17,
                            OffenseTypingId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 3,
                            DefenseTypingId = 15,
                            OffenseTypingId = 1,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 4,
                            DefenseTypingId = 13,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 5,
                            DefenseTypingId = 6,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 6,
                            DefenseTypingId = 12,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 7,
                            DefenseTypingId = 14,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 8,
                            DefenseTypingId = 2,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 9,
                            DefenseTypingId = 11,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 10,
                            DefenseTypingId = 4,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 11,
                            DefenseTypingId = 16,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 12,
                            DefenseTypingId = 12,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 13,
                            DefenseTypingId = 1,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 14,
                            DefenseTypingId = 11,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 15,
                            DefenseTypingId = 17,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 16,
                            DefenseTypingId = 13,
                            OffenseTypingId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 17,
                            DefenseTypingId = 18,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 18,
                            DefenseTypingId = 5,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 19,
                            DefenseTypingId = 7,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 20,
                            DefenseTypingId = 10,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 21,
                            DefenseTypingId = 15,
                            OffenseTypingId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 22,
                            DefenseTypingId = 2,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 23,
                            DefenseTypingId = 9,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 24,
                            DefenseTypingId = 11,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 25,
                            DefenseTypingId = 14,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 26,
                            DefenseTypingId = 6,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 27,
                            DefenseTypingId = 4,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 28,
                            DefenseTypingId = 13,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 29,
                            DefenseTypingId = 3,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 30,
                            DefenseTypingId = 6,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 31,
                            DefenseTypingId = 8,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 32,
                            DefenseTypingId = 11,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 33,
                            DefenseTypingId = 17,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 34,
                            DefenseTypingId = 9,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 35,
                            DefenseTypingId = 11,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 36,
                            DefenseTypingId = 4,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 37,
                            DefenseTypingId = 13,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 38,
                            DefenseTypingId = 14,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 39,
                            DefenseTypingId = 2,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 40,
                            DefenseTypingId = 5,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 41,
                            DefenseTypingId = 6,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 42,
                            DefenseTypingId = 7,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 43,
                            DefenseTypingId = 17,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 44,
                            DefenseTypingId = 18,
                            OffenseTypingId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 45,
                            DefenseTypingId = 6,
                            OffenseTypingId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 46,
                            DefenseTypingId = 7,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 47,
                            DefenseTypingId = 9,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 48,
                            DefenseTypingId = 11,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 49,
                            DefenseTypingId = 15,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 50,
                            DefenseTypingId = 5,
                            OffenseTypingId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 51,
                            DefenseTypingId = 4,
                            OffenseTypingId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 52,
                            DefenseTypingId = 14,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 53,
                            DefenseTypingId = 8,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 54,
                            DefenseTypingId = 6,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 55,
                            DefenseTypingId = 9,
                            OffenseTypingId = 8,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 56,
                            DefenseTypingId = 8,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 57,
                            DefenseTypingId = 2,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 58,
                            DefenseTypingId = 7,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 59,
                            DefenseTypingId = 11,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 60,
                            DefenseTypingId = 17,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 61,
                            DefenseTypingId = 13,
                            OffenseTypingId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 62,
                            DefenseTypingId = 6,
                            OffenseTypingId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 63,
                            DefenseTypingId = 5,
                            OffenseTypingId = 9,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 65,
                            DefenseTypingId = 7,
                            OffenseTypingId = 10,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 66,
                            DefenseTypingId = 10,
                            OffenseTypingId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 67,
                            DefenseTypingId = 17,
                            OffenseTypingId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 68,
                            DefenseTypingId = 16,
                            OffenseTypingId = 10,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 69,
                            DefenseTypingId = 13,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 70,
                            DefenseTypingId = 2,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 71,
                            DefenseTypingId = 5,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 72,
                            DefenseTypingId = 12,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 73,
                            DefenseTypingId = 3,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 74,
                            DefenseTypingId = 9,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 75,
                            DefenseTypingId = 17,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 76,
                            DefenseTypingId = 14,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 77,
                            DefenseTypingId = 5,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 78,
                            DefenseTypingId = 6,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 79,
                            DefenseTypingId = 9,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 80,
                            DefenseTypingId = 2,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 81,
                            DefenseTypingId = 12,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 82,
                            DefenseTypingId = 17,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 83,
                            DefenseTypingId = 4,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 84,
                            DefenseTypingId = 16,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 85,
                            DefenseTypingId = 6,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 86,
                            DefenseTypingId = 10,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 87,
                            DefenseTypingId = 18,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 88,
                            DefenseTypingId = 3,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 89,
                            DefenseTypingId = 2,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 90,
                            DefenseTypingId = 5,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 91,
                            DefenseTypingId = 15,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 92,
                            DefenseTypingId = 7,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 93,
                            DefenseTypingId = 17,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 94,
                            DefenseTypingId = 14,
                            OffenseTypingId = 14,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 95,
                            DefenseTypingId = 17,
                            OffenseTypingId = 14,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 96,
                            DefenseTypingId = 18,
                            OffenseTypingId = 14,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 97,
                            DefenseTypingId = 15,
                            OffenseTypingId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 98,
                            DefenseTypingId = 10,
                            OffenseTypingId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 99,
                            DefenseTypingId = 16,
                            OffenseTypingId = 15,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 100,
                            DefenseTypingId = 1,
                            OffenseTypingId = 15,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 101,
                            DefenseTypingId = 15,
                            OffenseTypingId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 102,
                            DefenseTypingId = 10,
                            OffenseTypingId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 103,
                            DefenseTypingId = 16,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 104,
                            DefenseTypingId = 18,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 105,
                            DefenseTypingId = 3,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 106,
                            DefenseTypingId = 18,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 107,
                            DefenseTypingId = 12,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 108,
                            DefenseTypingId = 11,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 109,
                            DefenseTypingId = 8,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 110,
                            DefenseTypingId = 2,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 111,
                            DefenseTypingId = 17,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 112,
                            DefenseTypingId = 4,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 113,
                            DefenseTypingId = 16,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 114,
                            DefenseTypingId = 14,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 115,
                            DefenseTypingId = 3,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 116,
                            DefenseTypingId = 2,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 117,
                            DefenseTypingId = 7,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 118,
                            DefenseTypingId = 17,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.Typing", b =>
                {
                    b.Property<int>("TypingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypingId");

                    b.ToTable("Typings");

                    b.HasData(
                        new
                        {
                            TypingId = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            TypingId = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            TypingId = 3,
                            Name = "Fighting"
                        },
                        new
                        {
                            TypingId = 4,
                            Name = "Water"
                        },
                        new
                        {
                            TypingId = 5,
                            Name = "Flying"
                        },
                        new
                        {
                            TypingId = 6,
                            Name = "Grass"
                        },
                        new
                        {
                            TypingId = 7,
                            Name = "Poison"
                        },
                        new
                        {
                            TypingId = 8,
                            Name = "Electric"
                        },
                        new
                        {
                            TypingId = 9,
                            Name = "Ground"
                        },
                        new
                        {
                            TypingId = 10,
                            Name = "Psychic"
                        },
                        new
                        {
                            TypingId = 11,
                            Name = "Rock"
                        },
                        new
                        {
                            TypingId = 12,
                            Name = "Ice"
                        },
                        new
                        {
                            TypingId = 13,
                            Name = "Bug"
                        },
                        new
                        {
                            TypingId = 14,
                            Name = "Dragon"
                        },
                        new
                        {
                            TypingId = 15,
                            Name = "Ghost"
                        },
                        new
                        {
                            TypingId = 16,
                            Name = "Dark"
                        },
                        new
                        {
                            TypingId = 17,
                            Name = "Steel"
                        },
                        new
                        {
                            TypingId = 18,
                            Name = "Fairy"
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.PokemonTyping", b =>
                {
                    b.HasOne("Pokemons.API.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonTypings")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pokemons.API.Models.Typing", "Typing")
                        .WithMany("PokemonTypings")
                        .HasForeignKey("TypingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Typing");
                });

            modelBuilder.Entity("Pokemons.API.Models.TypeEffect", b =>
                {
                    b.HasOne("Pokemons.API.Models.Typing", "DefenseTyping")
                        .WithMany("TypeDefense")
                        .HasForeignKey("DefenseTypingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pokemons.API.Models.Typing", "OffenseTyping")
                        .WithMany("TypeOffense")
                        .HasForeignKey("OffenseTypingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DefenseTyping");

                    b.Navigation("OffenseTyping");
                });

            modelBuilder.Entity("Pokemons.API.Models.Pokemon", b =>
                {
                    b.Navigation("PokemonTypings");
                });

            modelBuilder.Entity("Pokemons.API.Models.Typing", b =>
                {
                    b.Navigation("PokemonTypings");

                    b.Navigation("TypeDefense");

                    b.Navigation("TypeOffense");
                });
#pragma warning restore 612, 618
        }
    }
}
