// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokemons.API.Data;

namespace Pokemons.API.Migrations
{
    [DbContext(typeof(PokemonContext))]
    partial class PokemonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pokemons.API.Models.Pokemon", b =>
                {
                    b.Property<Guid>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EggGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokedexEntry")
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.HasIndex("PokedexEntry", "Generation")
                        .IsUnique();

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            PokemonId = new Guid("c6767aef-2570-4a06-a508-dabb633fa567"),
                            Classification = "Sleeping Pokemon",
                            EggGroup = "Monster",
                            Generation = 1,
                            Name = "Snorlax",
                            PokedexEntry = 143
                        },
                        new
                        {
                            PokemonId = new Guid("c2478ba4-6118-40b9-9746-8b4c1a12f0a4"),
                            Classification = "Blocking Pokemon",
                            EggGroup = "Field",
                            Generation = 8,
                            Name = "Obstagoon",
                            PokedexEntry = 598
                        },
                        new
                        {
                            PokemonId = new Guid("6ca5f605-d965-4795-80de-80bc09e1bf42"),
                            Classification = "Lizard Pokemon",
                            EggGroup = "Monster,Dragon",
                            Generation = 1,
                            Name = "Charmander",
                            PokedexEntry = 4
                        },
                        new
                        {
                            PokemonId = new Guid("0508dba5-c8a6-4f87-8adc-c6550b94dcab"),
                            Classification = "Sun Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Volcarona",
                            PokedexEntry = 637
                        },
                        new
                        {
                            PokemonId = new Guid("87a61f3c-3bc4-4a29-a1fe-5b3f2e1ecb9a"),
                            Classification = "Superpower Pokemon",
                            EggGroup = "Human-Like",
                            Generation = 1,
                            Name = "Machoke",
                            PokedexEntry = 67
                        },
                        new
                        {
                            PokemonId = new Guid("94395695-0736-4d79-b25e-d95520b29328"),
                            Classification = "Single Horn Pokemon",
                            EggGroup = "Bug",
                            Generation = 2,
                            Name = "Heracross",
                            PokedexEntry = 214
                        },
                        new
                        {
                            PokemonId = new Guid("3ea65225-f952-4549-b06a-6b7c4bb1c107"),
                            Classification = "Mud Fish Pokemon",
                            EggGroup = "Monster,Water 1",
                            Generation = 3,
                            Name = "Swampert",
                            PokedexEntry = 260
                        },
                        new
                        {
                            PokemonId = new Guid("27a14f98-963f-46e2-9b34-c5fb4faa42ec"),
                            Classification = "Mock Kelp Pokemon",
                            EggGroup = "Bug",
                            Generation = 6,
                            Name = "Skrelp",
                            PokedexEntry = 637
                        },
                        new
                        {
                            PokemonId = new Guid("abbe3e06-8cb6-45d3-8da1-51337b45e8d1"),
                            Classification = "Raven Pokemon",
                            EggGroup = "Flying",
                            Generation = 8,
                            Name = "Corviknight",
                            PokedexEntry = 823
                        },
                        new
                        {
                            PokemonId = new Guid("3d9744a6-7ba4-423d-913e-7f8765703ba4"),
                            Classification = "Balloon Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 4,
                            Name = "Drifloon",
                            PokedexEntry = 425
                        },
                        new
                        {
                            PokemonId = new Guid("97b58c44-e60e-45c2-ae5d-8b9af6c85946"),
                            Classification = "Sickle Grass Pokemon",
                            EggGroup = "Grass",
                            Generation = 7,
                            Name = "Fomantis",
                            PokedexEntry = 753
                        },
                        new
                        {
                            PokemonId = new Guid("e8e78a90-6f80-486f-9d2e-097de3b8b326"),
                            Classification = "Sea Lily Pokemon",
                            EggGroup = "Water 3",
                            Generation = 3,
                            Name = "Lileep",
                            PokedexEntry = 345
                        },
                        new
                        {
                            PokemonId = new Guid("1ecbff5d-0207-43f0-85c9-112c0f3dff44"),
                            Classification = "Poison Pin Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 7,
                            Name = "Naganadel",
                            PokedexEntry = 804
                        },
                        new
                        {
                            PokemonId = new Guid("58a1e17e-8308-4422-ab7b-baa6f2a5ddd4"),
                            Classification = "Bouquet Pokemon",
                            EggGroup = "Fairy,Grass",
                            Generation = 4,
                            Name = "Roserade",
                            PokedexEntry = 407
                        },
                        new
                        {
                            PokemonId = new Guid("d2a35562-a5f3-4bbf-bbd4-da6f4bc6c685"),
                            Classification = "Magnet Area Pokemon",
                            EggGroup = "Mineral",
                            Generation = 4,
                            Name = "Magnezone",
                            PokedexEntry = 462
                        },
                        new
                        {
                            PokemonId = new Guid("b35a9edb-ba73-4d3a-b228-59ea3ba3cdbd"),
                            Classification = "Deep Black Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 5,
                            Name = "Zekrom",
                            PokedexEntry = 644
                        },
                        new
                        {
                            PokemonId = new Guid("7c9e037a-cd44-420c-86b7-6290b1b3d4d2"),
                            Classification = "Automaton Pokemon",
                            EggGroup = "Mineral",
                            Generation = 5,
                            Name = "Golett",
                            PokedexEntry = 622
                        },
                        new
                        {
                            PokemonId = new Guid("45ad8ae0-4bd1-46c8-8a1b-13d547b98a2e"),
                            Classification = "Order Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 6,
                            Name = "Zygarde",
                            PokedexEntry = 718
                        },
                        new
                        {
                            PokemonId = new Guid("c7bb2593-e473-4964-b811-f807ac8c4227"),
                            Classification = "Psi Pokemon",
                            EggGroup = "Human-Like",
                            Generation = 1,
                            Name = "Abra",
                            PokedexEntry = 63
                        },
                        new
                        {
                            PokemonId = new Guid("1e7e232f-4005-4524-8c97-4a870cbecd44"),
                            Classification = "Bronze Bell Pokemon",
                            EggGroup = "Mineral",
                            Generation = 4,
                            Name = "Bronzong",
                            PokedexEntry = 437
                        },
                        new
                        {
                            PokemonId = new Guid("9503ff9c-c758-4696-bc90-d941779dca99"),
                            Classification = "Head Butt Pokemon",
                            EggGroup = "Monster",
                            Generation = 4,
                            Name = "Rampardos",
                            PokedexEntry = 409
                        },
                        new
                        {
                            PokemonId = new Guid("053a5141-9b56-4a85-8f69-04931a7010c2"),
                            Classification = "Tundra Pokemon",
                            EggGroup = "Monster",
                            Generation = 6,
                            Name = "Aurorus",
                            PokedexEntry = 699
                        },
                        new
                        {
                            PokemonId = new Guid("a95e64c7-4db4-4dec-86d6-766975d5f2c6"),
                            Classification = "Snow Hat Pokemon",
                            EggGroup = "Fairy,Mineral",
                            Generation = 3,
                            Name = "Snorunt",
                            PokedexEntry = 361
                        },
                        new
                        {
                            PokemonId = new Guid("6a776247-1d5e-43da-b3f3-7624db34b5e3"),
                            Classification = "Worm Pokemon",
                            EggGroup = "Bug",
                            Generation = 8,
                            Name = "Snom",
                            PokedexEntry = 872
                        },
                        new
                        {
                            PokemonId = new Guid("7697efcc-2fd4-47b9-8ff8-a3b2b8a6fe48"),
                            Classification = "Leaf-Wrapped Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Swadloon",
                            PokedexEntry = 541
                        },
                        new
                        {
                            PokemonId = new Guid("389fd12d-2de2-4580-bf23-deba613de135"),
                            Classification = "Curlipede Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Whirlipede",
                            PokedexEntry = 544
                        },
                        new
                        {
                            PokemonId = new Guid("5b78d2c1-3929-4851-bad2-928b4b899579"),
                            Classification = "Dragon Pokemon",
                            EggGroup = "Water 1,Dragon",
                            Generation = 1,
                            Name = "Dragonair",
                            PokedexEntry = 148
                        },
                        new
                        {
                            PokemonId = new Guid("bd11fef1-b32c-466f-9aac-0d904ccb4bc7"),
                            Classification = "Stealth Pokemon",
                            EggGroup = "Amorphous,Dragon",
                            Generation = 8,
                            Name = "Dragapult",
                            PokedexEntry = 887
                        },
                        new
                        {
                            PokemonId = new Guid("77031fbf-d613-4638-92f3-590bd8376520"),
                            Classification = "Screech Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 2,
                            Name = "Misdreavus",
                            PokedexEntry = 200
                        },
                        new
                        {
                            PokemonId = new Guid("3764f6da-00ed-4a68-aa3d-3131b29929ce"),
                            Classification = "Magical Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 4,
                            Name = "Mismagius",
                            PokedexEntry = 429
                        },
                        new
                        {
                            PokemonId = new Guid("571d3ed7-3b77-4f3c-a251-446dc30d02f6"),
                            Classification = "Wily Pokemon",
                            EggGroup = "Field,Grass",
                            Generation = 3,
                            Name = "Nuzleaf",
                            PokedexEntry = 274
                        },
                        new
                        {
                            PokemonId = new Guid("ff17e5a8-9300-4668-8b9f-6026d8b1472a"),
                            Classification = "Skunk Pokemon",
                            EggGroup = "Field",
                            Generation = 4,
                            Name = "Skuntank",
                            PokedexEntry = 435
                        },
                        new
                        {
                            PokemonId = new Guid("eb644554-6660-4ecc-b08b-d09ea53abcd9"),
                            Classification = "Iron Armor Pokemon",
                            EggGroup = "Monster",
                            Generation = 3,
                            Name = "Aggron",
                            PokedexEntry = 306
                        },
                        new
                        {
                            PokemonId = new Guid("2ee76c5d-3179-4930-acd7-44b4f9775523"),
                            Classification = "Thorn Pod Pokemon",
                            EggGroup = "Grass,Mineral",
                            Generation = 5,
                            Name = "Ferrothorn",
                            PokedexEntry = 598
                        },
                        new
                        {
                            PokemonId = new Guid("edcdebde-d477-4dbb-b5bf-5bcd1b1b2007"),
                            Classification = "Balloon Pokemon",
                            EggGroup = "Fairy",
                            Generation = 1,
                            Name = "Jigglypuff",
                            PokedexEntry = 39
                        },
                        new
                        {
                            PokemonId = new Guid("42b1c658-75c9-4bcf-95a8-5dc3cec4942c"),
                            Classification = "Embrace Pokemon",
                            EggGroup = "Human-Like,Amorphous",
                            Generation = 3,
                            Name = "Gardevoir",
                            PokedexEntry = 282
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.PokemonTyping", b =>
                {
                    b.Property<Guid>("PokemonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypingId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "TypingId");

                    b.HasIndex("TypingId");

                    b.ToTable("PokemonTyping");

                    b.HasData(
                        new
                        {
                            PokemonId = new Guid("c6767aef-2570-4a06-a508-dabb633fa567"),
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = new Guid("c2478ba4-6118-40b9-9746-8b4c1a12f0a4"),
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = new Guid("c2478ba4-6118-40b9-9746-8b4c1a12f0a4"),
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = new Guid("6ca5f605-d965-4795-80de-80bc09e1bf42"),
                            TypingId = 2
                        },
                        new
                        {
                            PokemonId = new Guid("0508dba5-c8a6-4f87-8adc-c6550b94dcab"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("0508dba5-c8a6-4f87-8adc-c6550b94dcab"),
                            TypingId = 2
                        },
                        new
                        {
                            PokemonId = new Guid("87a61f3c-3bc4-4a29-a1fe-5b3f2e1ecb9a"),
                            TypingId = 3
                        },
                        new
                        {
                            PokemonId = new Guid("94395695-0736-4d79-b25e-d95520b29328"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("94395695-0736-4d79-b25e-d95520b29328"),
                            TypingId = 3
                        },
                        new
                        {
                            PokemonId = new Guid("3ea65225-f952-4549-b06a-6b7c4bb1c107"),
                            TypingId = 4
                        },
                        new
                        {
                            PokemonId = new Guid("3ea65225-f952-4549-b06a-6b7c4bb1c107"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("27a14f98-963f-46e2-9b34-c5fb4faa42ec"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("27a14f98-963f-46e2-9b34-c5fb4faa42ec"),
                            TypingId = 4
                        },
                        new
                        {
                            PokemonId = new Guid("abbe3e06-8cb6-45d3-8da1-51337b45e8d1"),
                            TypingId = 5
                        },
                        new
                        {
                            PokemonId = new Guid("abbe3e06-8cb6-45d3-8da1-51337b45e8d1"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("3d9744a6-7ba4-423d-913e-7f8765703ba4"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("3d9744a6-7ba4-423d-913e-7f8765703ba4"),
                            TypingId = 5
                        },
                        new
                        {
                            PokemonId = new Guid("97b58c44-e60e-45c2-ae5d-8b9af6c85946"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("e8e78a90-6f80-486f-9d2e-097de3b8b326"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("e8e78a90-6f80-486f-9d2e-097de3b8b326"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("1ecbff5d-0207-43f0-85c9-112c0f3dff44"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("1ecbff5d-0207-43f0-85c9-112c0f3dff44"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("58a1e17e-8308-4422-ab7b-baa6f2a5ddd4"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("58a1e17e-8308-4422-ab7b-baa6f2a5ddd4"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("d2a35562-a5f3-4bbf-bbd4-da6f4bc6c685"),
                            TypingId = 8
                        },
                        new
                        {
                            PokemonId = new Guid("d2a35562-a5f3-4bbf-bbd4-da6f4bc6c685"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("b35a9edb-ba73-4d3a-b228-59ea3ba3cdbd"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("b35a9edb-ba73-4d3a-b228-59ea3ba3cdbd"),
                            TypingId = 8
                        },
                        new
                        {
                            PokemonId = new Guid("7c9e037a-cd44-420c-86b7-6290b1b3d4d2"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("7c9e037a-cd44-420c-86b7-6290b1b3d4d2"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("45ad8ae0-4bd1-46c8-8a1b-13d547b98a2e"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("45ad8ae0-4bd1-46c8-8a1b-13d547b98a2e"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("c7bb2593-e473-4964-b811-f807ac8c4227"),
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = new Guid("1e7e232f-4005-4524-8c97-4a870cbecd44"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("1e7e232f-4005-4524-8c97-4a870cbecd44"),
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = new Guid("9503ff9c-c758-4696-bc90-d941779dca99"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("053a5141-9b56-4a85-8f69-04931a7010c2"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("053a5141-9b56-4a85-8f69-04931a7010c2"),
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = new Guid("a95e64c7-4db4-4dec-86d6-766975d5f2c6"),
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = new Guid("6a776247-1d5e-43da-b3f3-7624db34b5e3"),
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = new Guid("6a776247-1d5e-43da-b3f3-7624db34b5e3"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("7697efcc-2fd4-47b9-8ff8-a3b2b8a6fe48"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("7697efcc-2fd4-47b9-8ff8-a3b2b8a6fe48"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("389fd12d-2de2-4580-bf23-deba613de135"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("389fd12d-2de2-4580-bf23-deba613de135"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("5b78d2c1-3929-4851-bad2-928b4b899579"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("bd11fef1-b32c-466f-9aac-0d904ccb4bc7"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("bd11fef1-b32c-466f-9aac-0d904ccb4bc7"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("77031fbf-d613-4638-92f3-590bd8376520"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("3764f6da-00ed-4a68-aa3d-3131b29929ce"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("571d3ed7-3b77-4f3c-a251-446dc30d02f6"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("571d3ed7-3b77-4f3c-a251-446dc30d02f6"),
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = new Guid("ff17e5a8-9300-4668-8b9f-6026d8b1472a"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("ff17e5a8-9300-4668-8b9f-6026d8b1472a"),
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = new Guid("eb644554-6660-4ecc-b08b-d09ea53abcd9"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("eb644554-6660-4ecc-b08b-d09ea53abcd9"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("2ee76c5d-3179-4930-acd7-44b4f9775523"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("2ee76c5d-3179-4930-acd7-44b4f9775523"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("edcdebde-d477-4dbb-b5bf-5bcd1b1b2007"),
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = new Guid("edcdebde-d477-4dbb-b5bf-5bcd1b1b2007"),
                            TypingId = 18
                        },
                        new
                        {
                            PokemonId = new Guid("42b1c658-75c9-4bcf-95a8-5dc3cec4942c"),
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = new Guid("42b1c658-75c9-4bcf-95a8-5dc3cec4942c"),
                            TypingId = 18
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.TypeEffect", b =>
                {
                    b.Property<int>("TypeEffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DefenseTypingId")
                        .HasColumnType("int");

                    b.Property<int>("OffenseTypingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TypeEffectId");

                    b.HasIndex("DefenseTypingId");

                    b.HasIndex("OffenseTypingId");

                    b.ToTable("TypeEffects");

                    b.HasData(
                        new
                        {
                            TypeEffectId = 1,
                            DefenseTypingId = 11,
                            OffenseTypingId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 2,
                            DefenseTypingId = 17,
                            OffenseTypingId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 3,
                            DefenseTypingId = 15,
                            OffenseTypingId = 1,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 4,
                            DefenseTypingId = 13,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 5,
                            DefenseTypingId = 6,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 6,
                            DefenseTypingId = 12,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 7,
                            DefenseTypingId = 14,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 8,
                            DefenseTypingId = 2,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 9,
                            DefenseTypingId = 11,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 10,
                            DefenseTypingId = 4,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 11,
                            DefenseTypingId = 16,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 12,
                            DefenseTypingId = 12,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 13,
                            DefenseTypingId = 1,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 14,
                            DefenseTypingId = 11,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 15,
                            DefenseTypingId = 17,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 16,
                            DefenseTypingId = 13,
                            OffenseTypingId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 17,
                            DefenseTypingId = 18,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 18,
                            DefenseTypingId = 5,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 19,
                            DefenseTypingId = 7,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 20,
                            DefenseTypingId = 10,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 21,
                            DefenseTypingId = 15,
                            OffenseTypingId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 22,
                            DefenseTypingId = 2,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 23,
                            DefenseTypingId = 9,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 24,
                            DefenseTypingId = 11,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 25,
                            DefenseTypingId = 14,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 26,
                            DefenseTypingId = 6,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 27,
                            DefenseTypingId = 4,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 28,
                            DefenseTypingId = 13,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 29,
                            DefenseTypingId = 3,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 30,
                            DefenseTypingId = 6,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 31,
                            DefenseTypingId = 8,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 32,
                            DefenseTypingId = 11,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 33,
                            DefenseTypingId = 17,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 34,
                            DefenseTypingId = 9,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 35,
                            DefenseTypingId = 11,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 36,
                            DefenseTypingId = 4,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 37,
                            DefenseTypingId = 13,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 38,
                            DefenseTypingId = 14,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 39,
                            DefenseTypingId = 2,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 40,
                            DefenseTypingId = 5,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 41,
                            DefenseTypingId = 6,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 42,
                            DefenseTypingId = 7,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 43,
                            DefenseTypingId = 17,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 44,
                            DefenseTypingId = 18,
                            OffenseTypingId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 45,
                            DefenseTypingId = 6,
                            OffenseTypingId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 46,
                            DefenseTypingId = 7,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 47,
                            DefenseTypingId = 9,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 48,
                            DefenseTypingId = 11,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 49,
                            DefenseTypingId = 15,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 50,
                            DefenseTypingId = 5,
                            OffenseTypingId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 51,
                            DefenseTypingId = 4,
                            OffenseTypingId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 52,
                            DefenseTypingId = 14,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 53,
                            DefenseTypingId = 8,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 54,
                            DefenseTypingId = 6,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 55,
                            DefenseTypingId = 9,
                            OffenseTypingId = 8,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 56,
                            DefenseTypingId = 8,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 57,
                            DefenseTypingId = 2,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 58,
                            DefenseTypingId = 7,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 59,
                            DefenseTypingId = 11,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 60,
                            DefenseTypingId = 17,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 61,
                            DefenseTypingId = 13,
                            OffenseTypingId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 62,
                            DefenseTypingId = 6,
                            OffenseTypingId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 63,
                            DefenseTypingId = 5,
                            OffenseTypingId = 9,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 64,
                            DefenseTypingId = 7,
                            OffenseTypingId = 10,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 65,
                            DefenseTypingId = 10,
                            OffenseTypingId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 66,
                            DefenseTypingId = 17,
                            OffenseTypingId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 67,
                            DefenseTypingId = 16,
                            OffenseTypingId = 10,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 68,
                            DefenseTypingId = 13,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 69,
                            DefenseTypingId = 2,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 70,
                            DefenseTypingId = 5,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 71,
                            DefenseTypingId = 12,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 72,
                            DefenseTypingId = 3,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 73,
                            DefenseTypingId = 9,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 74,
                            DefenseTypingId = 17,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 75,
                            DefenseTypingId = 14,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 76,
                            DefenseTypingId = 5,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 77,
                            DefenseTypingId = 6,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 78,
                            DefenseTypingId = 9,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 79,
                            DefenseTypingId = 2,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 80,
                            DefenseTypingId = 12,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 81,
                            DefenseTypingId = 17,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 82,
                            DefenseTypingId = 4,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 83,
                            DefenseTypingId = 16,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 84,
                            DefenseTypingId = 6,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 85,
                            DefenseTypingId = 10,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 86,
                            DefenseTypingId = 18,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 87,
                            DefenseTypingId = 3,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 88,
                            DefenseTypingId = 2,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 89,
                            DefenseTypingId = 5,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 90,
                            DefenseTypingId = 15,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 91,
                            DefenseTypingId = 7,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 92,
                            DefenseTypingId = 17,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 93,
                            DefenseTypingId = 14,
                            OffenseTypingId = 14,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 94,
                            DefenseTypingId = 17,
                            OffenseTypingId = 14,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 95,
                            DefenseTypingId = 18,
                            OffenseTypingId = 14,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 96,
                            DefenseTypingId = 15,
                            OffenseTypingId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 97,
                            DefenseTypingId = 10,
                            OffenseTypingId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 98,
                            DefenseTypingId = 16,
                            OffenseTypingId = 15,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 99,
                            DefenseTypingId = 1,
                            OffenseTypingId = 15,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 100,
                            DefenseTypingId = 15,
                            OffenseTypingId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 101,
                            DefenseTypingId = 10,
                            OffenseTypingId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 102,
                            DefenseTypingId = 16,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 103,
                            DefenseTypingId = 18,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 104,
                            DefenseTypingId = 3,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 105,
                            DefenseTypingId = 18,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 106,
                            DefenseTypingId = 12,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 107,
                            DefenseTypingId = 11,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 108,
                            DefenseTypingId = 8,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 109,
                            DefenseTypingId = 2,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 110,
                            DefenseTypingId = 17,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 111,
                            DefenseTypingId = 4,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 112,
                            DefenseTypingId = 16,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 113,
                            DefenseTypingId = 14,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 114,
                            DefenseTypingId = 3,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 115,
                            DefenseTypingId = 2,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 116,
                            DefenseTypingId = 7,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 117,
                            DefenseTypingId = 17,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.Typing", b =>
                {
                    b.Property<int>("TypingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypingId");

                    b.ToTable("Typings");

                    b.HasData(
                        new
                        {
                            TypingId = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            TypingId = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            TypingId = 3,
                            Name = "Fighting"
                        },
                        new
                        {
                            TypingId = 4,
                            Name = "Water"
                        },
                        new
                        {
                            TypingId = 5,
                            Name = "Flying"
                        },
                        new
                        {
                            TypingId = 6,
                            Name = "Grass"
                        },
                        new
                        {
                            TypingId = 7,
                            Name = "Poison"
                        },
                        new
                        {
                            TypingId = 8,
                            Name = "Electric"
                        },
                        new
                        {
                            TypingId = 9,
                            Name = "Ground"
                        },
                        new
                        {
                            TypingId = 10,
                            Name = "Psychic"
                        },
                        new
                        {
                            TypingId = 11,
                            Name = "Rock"
                        },
                        new
                        {
                            TypingId = 12,
                            Name = "Ice"
                        },
                        new
                        {
                            TypingId = 13,
                            Name = "Bug"
                        },
                        new
                        {
                            TypingId = 14,
                            Name = "Dragon"
                        },
                        new
                        {
                            TypingId = 15,
                            Name = "Ghost"
                        },
                        new
                        {
                            TypingId = 16,
                            Name = "Dark"
                        },
                        new
                        {
                            TypingId = 17,
                            Name = "Steel"
                        },
                        new
                        {
                            TypingId = 18,
                            Name = "Fairy"
                        });
                });

            modelBuilder.Entity("Pokemons.API.Models.PokemonTyping", b =>
                {
                    b.HasOne("Pokemons.API.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonTypings")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pokemons.API.Models.Typing", "Typing")
                        .WithMany("PokemonTypings")
                        .HasForeignKey("TypingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Typing");
                });

            modelBuilder.Entity("Pokemons.API.Models.TypeEffect", b =>
                {
                    b.HasOne("Pokemons.API.Models.Typing", "DefenseTyping")
                        .WithMany("TypeDefense")
                        .HasForeignKey("DefenseTypingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pokemons.API.Models.Typing", "OffenseTyping")
                        .WithMany("TypeOffense")
                        .HasForeignKey("OffenseTypingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DefenseTyping");

                    b.Navigation("OffenseTyping");
                });

            modelBuilder.Entity("Pokemons.API.Models.Pokemon", b =>
                {
                    b.Navigation("PokemonTypings");
                });

            modelBuilder.Entity("Pokemons.API.Models.Typing", b =>
                {
                    b.Navigation("PokemonTypings");

                    b.Navigation("TypeDefense");

                    b.Navigation("TypeOffense");
                });
#pragma warning restore 612, 618
        }
    }
}
