// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonAPI.Data;

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20210427124143_first migration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PokemonAPI.Models.Pokemon", b =>
                {
                    b.Property<Guid>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EggGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokedexEntry")
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.HasIndex("PokedexEntry", "Generation")
                        .IsUnique();

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            PokemonId = new Guid("1eecc83a-39c1-42e6-a863-1b930fe8fff7"),
                            Classification = "Sleeping Pokemon",
                            EggGroup = "Monster",
                            Generation = 1,
                            Name = "Snorlax",
                            PokedexEntry = 143
                        },
                        new
                        {
                            PokemonId = new Guid("c1956f38-94d9-40bc-8420-ad0f75b73dcf"),
                            Classification = "Blocking Pokemon",
                            EggGroup = "Field",
                            Generation = 8,
                            Name = "Obstagoon",
                            PokedexEntry = 598
                        },
                        new
                        {
                            PokemonId = new Guid("7fd1e9b6-ed9e-4f8d-808b-75119a428c60"),
                            Classification = "Lizard Pokemon",
                            EggGroup = "Monster,Dragon",
                            Generation = 1,
                            Name = "Charmander",
                            PokedexEntry = 4
                        },
                        new
                        {
                            PokemonId = new Guid("bfca5085-3d5a-4055-80a9-4e1bd183972e"),
                            Classification = "Sun Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Volcarona",
                            PokedexEntry = 637
                        },
                        new
                        {
                            PokemonId = new Guid("6bae96ad-2523-442f-83f9-7b0b9e5c15ec"),
                            Classification = "Superpower Pokemon",
                            EggGroup = "Human-Like",
                            Generation = 1,
                            Name = "Machoke",
                            PokedexEntry = 67
                        },
                        new
                        {
                            PokemonId = new Guid("c1d0a18d-a4e8-4f0c-8b27-f80743383ee2"),
                            Classification = "Single Horn Pokemon",
                            EggGroup = "Bug",
                            Generation = 2,
                            Name = "Heracross",
                            PokedexEntry = 214
                        },
                        new
                        {
                            PokemonId = new Guid("a878374a-c734-49d4-86be-464182d63a57"),
                            Classification = "Mud Fish Pokemon",
                            EggGroup = "Monster,Water 1",
                            Generation = 3,
                            Name = "Swampert",
                            PokedexEntry = 260
                        },
                        new
                        {
                            PokemonId = new Guid("6dab1d48-fd04-4f4a-8b3d-a243e76b8a2e"),
                            Classification = "Mock Kelp Pokemon",
                            EggGroup = "Bug",
                            Generation = 6,
                            Name = "Skrelp",
                            PokedexEntry = 637
                        },
                        new
                        {
                            PokemonId = new Guid("8e001855-2ace-4494-86fa-c0dcc5060b49"),
                            Classification = "Raven Pokemon",
                            EggGroup = "Flying",
                            Generation = 8,
                            Name = "Corviknight",
                            PokedexEntry = 823
                        },
                        new
                        {
                            PokemonId = new Guid("789becb6-eb99-4ae6-839a-730e8043365f"),
                            Classification = "Balloon Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 4,
                            Name = "Drifloon",
                            PokedexEntry = 425
                        },
                        new
                        {
                            PokemonId = new Guid("390a686c-52f1-4c37-97da-3a4447e2a3a9"),
                            Classification = "Sickle Grass Pokemon",
                            EggGroup = "Grass",
                            Generation = 7,
                            Name = "Fomantis",
                            PokedexEntry = 753
                        },
                        new
                        {
                            PokemonId = new Guid("c420ca5c-d71b-45e8-992a-7523bc24f2dd"),
                            Classification = "Sea Lily Pokemon",
                            EggGroup = "Water 3",
                            Generation = 3,
                            Name = "Lileep",
                            PokedexEntry = 345
                        },
                        new
                        {
                            PokemonId = new Guid("fca2f1a3-ccca-4ec8-9f6a-c065ea790bd0"),
                            Classification = "Poison Pin Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 7,
                            Name = "Naganadel",
                            PokedexEntry = 804
                        },
                        new
                        {
                            PokemonId = new Guid("425a094a-792a-4203-b476-64ada11d276f"),
                            Classification = "Bouquet Pokemon",
                            EggGroup = "Fairy,Grass",
                            Generation = 4,
                            Name = "Roserade",
                            PokedexEntry = 407
                        },
                        new
                        {
                            PokemonId = new Guid("1ebfff64-f258-468b-9940-52d10dc18a2d"),
                            Classification = "Magnet Area Pokemon",
                            EggGroup = "Mineral",
                            Generation = 4,
                            Name = "Magnezone",
                            PokedexEntry = 462
                        },
                        new
                        {
                            PokemonId = new Guid("6baf9079-d024-4103-8a43-f3219d9438a3"),
                            Classification = "Deep Black Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 5,
                            Name = "Zekrom",
                            PokedexEntry = 644
                        },
                        new
                        {
                            PokemonId = new Guid("9a848905-50b9-4420-8cb0-554cd13e2069"),
                            Classification = "Automaton Pokemon",
                            EggGroup = "Mineral",
                            Generation = 5,
                            Name = "Golett",
                            PokedexEntry = 622
                        },
                        new
                        {
                            PokemonId = new Guid("c8877bc4-2d18-410c-9e7d-323ae59a16a5"),
                            Classification = "Order Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 6,
                            Name = "Zygarde",
                            PokedexEntry = 718
                        },
                        new
                        {
                            PokemonId = new Guid("a124d796-0abc-444b-8abd-1d60a16d24e2"),
                            Classification = "Psi Pokemon",
                            EggGroup = "Human-Like",
                            Generation = 1,
                            Name = "Abra",
                            PokedexEntry = 63
                        },
                        new
                        {
                            PokemonId = new Guid("b73d87c6-e6fd-4f64-ba3e-2b1da37a51d0"),
                            Classification = "Bronze Bell Pokemon",
                            EggGroup = "Mineral",
                            Generation = 4,
                            Name = "Bronzong",
                            PokedexEntry = 437
                        },
                        new
                        {
                            PokemonId = new Guid("d50a0299-86f0-4f36-a57c-2a460870b8a9"),
                            Classification = "Head Butt Pokemon",
                            EggGroup = "Monster",
                            Generation = 4,
                            Name = "Rampardos",
                            PokedexEntry = 409
                        },
                        new
                        {
                            PokemonId = new Guid("07cb5925-f9aa-41cc-9311-58880ff220d1"),
                            Classification = "Tundra Pokemon",
                            EggGroup = "Monster",
                            Generation = 6,
                            Name = "Aurorus",
                            PokedexEntry = 699
                        },
                        new
                        {
                            PokemonId = new Guid("9e7384bb-3314-46e6-b864-ecd8a87a090f"),
                            Classification = "Snow Hat Pokemon",
                            EggGroup = "Fairy,Mineral",
                            Generation = 3,
                            Name = "Snorunt",
                            PokedexEntry = 361
                        },
                        new
                        {
                            PokemonId = new Guid("e847d5d7-fd37-43a4-bd69-bc2e12b19c68"),
                            Classification = "Worm Pokemon",
                            EggGroup = "Bug",
                            Generation = 8,
                            Name = "Snom",
                            PokedexEntry = 872
                        },
                        new
                        {
                            PokemonId = new Guid("a653b452-9a39-4e03-bfd7-d44fb88ac9fb"),
                            Classification = "Leaf-Wrapped Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Swadloon",
                            PokedexEntry = 541
                        },
                        new
                        {
                            PokemonId = new Guid("2b149444-2b7c-48fb-a0cf-3835a8c4efea"),
                            Classification = "Curlipede Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Whirlipede",
                            PokedexEntry = 544
                        },
                        new
                        {
                            PokemonId = new Guid("fa7b7ae4-9dd7-490e-974b-be6ecf97b044"),
                            Classification = "Dragon Pokemon",
                            EggGroup = "Water 1,Dragon",
                            Generation = 1,
                            Name = "Dragonair",
                            PokedexEntry = 148
                        },
                        new
                        {
                            PokemonId = new Guid("cc8da5c0-2439-461a-8624-b281f9847089"),
                            Classification = "Stealth Pokemon",
                            EggGroup = "Amorphous,Dragon",
                            Generation = 8,
                            Name = "Dragapult",
                            PokedexEntry = 887
                        },
                        new
                        {
                            PokemonId = new Guid("08df9cd6-e45e-4d86-a3f1-73c2b661737a"),
                            Classification = "Screech Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 2,
                            Name = "Misdreavus",
                            PokedexEntry = 200
                        },
                        new
                        {
                            PokemonId = new Guid("b7bda1aa-4716-4a1b-9e6f-f8edff7b4663"),
                            Classification = "Magical Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 4,
                            Name = "Mismagius",
                            PokedexEntry = 429
                        },
                        new
                        {
                            PokemonId = new Guid("76b7eead-fde1-43ef-83fb-29a29efde6eb"),
                            Classification = "Wily Pokemon",
                            EggGroup = "Field,Grass",
                            Generation = 3,
                            Name = "Nuzleaf",
                            PokedexEntry = 274
                        },
                        new
                        {
                            PokemonId = new Guid("d7d951f8-7d61-4c1d-b4d5-eeecc263594c"),
                            Classification = "Skunk Pokemon",
                            EggGroup = "Field",
                            Generation = 4,
                            Name = "Skuntank",
                            PokedexEntry = 435
                        },
                        new
                        {
                            PokemonId = new Guid("4d0c3dc4-50bc-4176-9bd9-8ba9d55646d4"),
                            Classification = "Iron Armor Pokemon",
                            EggGroup = "Monster",
                            Generation = 3,
                            Name = "Aggron",
                            PokedexEntry = 306
                        },
                        new
                        {
                            PokemonId = new Guid("1f6dde95-0da5-4571-94e6-a2187109e2e2"),
                            Classification = "Thorn Pod Pokemon",
                            EggGroup = "Grass,Mineral",
                            Generation = 5,
                            Name = "Ferrothorn",
                            PokedexEntry = 598
                        },
                        new
                        {
                            PokemonId = new Guid("dc0eb60f-7a18-495c-a168-36ccefbcbb71"),
                            Classification = "Balloon Pokemon",
                            EggGroup = "Fairy",
                            Generation = 1,
                            Name = "Jigglypuff",
                            PokedexEntry = 39
                        },
                        new
                        {
                            PokemonId = new Guid("63579e21-0ade-4ae2-b430-3125f907fba8"),
                            Classification = "Embrace Pokemon",
                            EggGroup = "Human-Like,Amorphous",
                            Generation = 3,
                            Name = "Gardevoir",
                            PokedexEntry = 282
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonTyping", b =>
                {
                    b.Property<Guid>("PokemonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypingId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "TypingId");

                    b.HasIndex("TypingId");

                    b.ToTable("PokemonTyping");

                    b.HasData(
                        new
                        {
                            PokemonId = new Guid("1eecc83a-39c1-42e6-a863-1b930fe8fff7"),
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = new Guid("c1956f38-94d9-40bc-8420-ad0f75b73dcf"),
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = new Guid("c1956f38-94d9-40bc-8420-ad0f75b73dcf"),
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = new Guid("7fd1e9b6-ed9e-4f8d-808b-75119a428c60"),
                            TypingId = 2
                        },
                        new
                        {
                            PokemonId = new Guid("bfca5085-3d5a-4055-80a9-4e1bd183972e"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("bfca5085-3d5a-4055-80a9-4e1bd183972e"),
                            TypingId = 2
                        },
                        new
                        {
                            PokemonId = new Guid("6bae96ad-2523-442f-83f9-7b0b9e5c15ec"),
                            TypingId = 3
                        },
                        new
                        {
                            PokemonId = new Guid("c1d0a18d-a4e8-4f0c-8b27-f80743383ee2"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("c1d0a18d-a4e8-4f0c-8b27-f80743383ee2"),
                            TypingId = 3
                        },
                        new
                        {
                            PokemonId = new Guid("a878374a-c734-49d4-86be-464182d63a57"),
                            TypingId = 4
                        },
                        new
                        {
                            PokemonId = new Guid("a878374a-c734-49d4-86be-464182d63a57"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("6dab1d48-fd04-4f4a-8b3d-a243e76b8a2e"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("6dab1d48-fd04-4f4a-8b3d-a243e76b8a2e"),
                            TypingId = 4
                        },
                        new
                        {
                            PokemonId = new Guid("8e001855-2ace-4494-86fa-c0dcc5060b49"),
                            TypingId = 5
                        },
                        new
                        {
                            PokemonId = new Guid("8e001855-2ace-4494-86fa-c0dcc5060b49"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("789becb6-eb99-4ae6-839a-730e8043365f"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("789becb6-eb99-4ae6-839a-730e8043365f"),
                            TypingId = 5
                        },
                        new
                        {
                            PokemonId = new Guid("390a686c-52f1-4c37-97da-3a4447e2a3a9"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("c420ca5c-d71b-45e8-992a-7523bc24f2dd"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("c420ca5c-d71b-45e8-992a-7523bc24f2dd"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("fca2f1a3-ccca-4ec8-9f6a-c065ea790bd0"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("fca2f1a3-ccca-4ec8-9f6a-c065ea790bd0"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("425a094a-792a-4203-b476-64ada11d276f"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("425a094a-792a-4203-b476-64ada11d276f"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("1ebfff64-f258-468b-9940-52d10dc18a2d"),
                            TypingId = 8
                        },
                        new
                        {
                            PokemonId = new Guid("1ebfff64-f258-468b-9940-52d10dc18a2d"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("6baf9079-d024-4103-8a43-f3219d9438a3"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("6baf9079-d024-4103-8a43-f3219d9438a3"),
                            TypingId = 8
                        },
                        new
                        {
                            PokemonId = new Guid("9a848905-50b9-4420-8cb0-554cd13e2069"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("9a848905-50b9-4420-8cb0-554cd13e2069"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("c8877bc4-2d18-410c-9e7d-323ae59a16a5"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("c8877bc4-2d18-410c-9e7d-323ae59a16a5"),
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = new Guid("a124d796-0abc-444b-8abd-1d60a16d24e2"),
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = new Guid("b73d87c6-e6fd-4f64-ba3e-2b1da37a51d0"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("b73d87c6-e6fd-4f64-ba3e-2b1da37a51d0"),
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = new Guid("d50a0299-86f0-4f36-a57c-2a460870b8a9"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("07cb5925-f9aa-41cc-9311-58880ff220d1"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("07cb5925-f9aa-41cc-9311-58880ff220d1"),
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = new Guid("9e7384bb-3314-46e6-b864-ecd8a87a090f"),
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = new Guid("e847d5d7-fd37-43a4-bd69-bc2e12b19c68"),
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = new Guid("e847d5d7-fd37-43a4-bd69-bc2e12b19c68"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("a653b452-9a39-4e03-bfd7-d44fb88ac9fb"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("a653b452-9a39-4e03-bfd7-d44fb88ac9fb"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("2b149444-2b7c-48fb-a0cf-3835a8c4efea"),
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = new Guid("2b149444-2b7c-48fb-a0cf-3835a8c4efea"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("fa7b7ae4-9dd7-490e-974b-be6ecf97b044"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("cc8da5c0-2439-461a-8624-b281f9847089"),
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = new Guid("cc8da5c0-2439-461a-8624-b281f9847089"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("08df9cd6-e45e-4d86-a3f1-73c2b661737a"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("b7bda1aa-4716-4a1b-9e6f-f8edff7b4663"),
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = new Guid("76b7eead-fde1-43ef-83fb-29a29efde6eb"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("76b7eead-fde1-43ef-83fb-29a29efde6eb"),
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = new Guid("d7d951f8-7d61-4c1d-b4d5-eeecc263594c"),
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = new Guid("d7d951f8-7d61-4c1d-b4d5-eeecc263594c"),
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = new Guid("4d0c3dc4-50bc-4176-9bd9-8ba9d55646d4"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("4d0c3dc4-50bc-4176-9bd9-8ba9d55646d4"),
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = new Guid("1f6dde95-0da5-4571-94e6-a2187109e2e2"),
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = new Guid("1f6dde95-0da5-4571-94e6-a2187109e2e2"),
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = new Guid("dc0eb60f-7a18-495c-a168-36ccefbcbb71"),
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = new Guid("dc0eb60f-7a18-495c-a168-36ccefbcbb71"),
                            TypingId = 18
                        },
                        new
                        {
                            PokemonId = new Guid("63579e21-0ade-4ae2-b430-3125f907fba8"),
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = new Guid("63579e21-0ade-4ae2-b430-3125f907fba8"),
                            TypingId = 18
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.TypeEffect", b =>
                {
                    b.Property<int>("TypeEffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DefenseTypingId")
                        .HasColumnType("int");

                    b.Property<int>("OffenseTypingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TypeEffectId");

                    b.HasIndex("DefenseTypingId");

                    b.HasIndex("OffenseTypingId");

                    b.ToTable("TypeEffects");

                    b.HasData(
                        new
                        {
                            TypeEffectId = 1,
                            DefenseTypingId = 11,
                            OffenseTypingId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 2,
                            DefenseTypingId = 17,
                            OffenseTypingId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 3,
                            DefenseTypingId = 15,
                            OffenseTypingId = 1,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 4,
                            DefenseTypingId = 13,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 5,
                            DefenseTypingId = 6,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 6,
                            DefenseTypingId = 12,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 7,
                            DefenseTypingId = 14,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 8,
                            DefenseTypingId = 2,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 9,
                            DefenseTypingId = 11,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 10,
                            DefenseTypingId = 4,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 11,
                            DefenseTypingId = 16,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 12,
                            DefenseTypingId = 12,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 13,
                            DefenseTypingId = 1,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 14,
                            DefenseTypingId = 11,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 15,
                            DefenseTypingId = 17,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 16,
                            DefenseTypingId = 13,
                            OffenseTypingId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 17,
                            DefenseTypingId = 18,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 18,
                            DefenseTypingId = 5,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 19,
                            DefenseTypingId = 7,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 20,
                            DefenseTypingId = 10,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 21,
                            DefenseTypingId = 15,
                            OffenseTypingId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 22,
                            DefenseTypingId = 2,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 23,
                            DefenseTypingId = 9,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 24,
                            DefenseTypingId = 11,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 25,
                            DefenseTypingId = 14,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 26,
                            DefenseTypingId = 6,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 27,
                            DefenseTypingId = 4,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 28,
                            DefenseTypingId = 13,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 29,
                            DefenseTypingId = 3,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 30,
                            DefenseTypingId = 6,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 31,
                            DefenseTypingId = 8,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 32,
                            DefenseTypingId = 11,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 33,
                            DefenseTypingId = 17,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 34,
                            DefenseTypingId = 9,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 35,
                            DefenseTypingId = 11,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 36,
                            DefenseTypingId = 4,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 37,
                            DefenseTypingId = 13,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 38,
                            DefenseTypingId = 14,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 39,
                            DefenseTypingId = 2,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 40,
                            DefenseTypingId = 5,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 41,
                            DefenseTypingId = 6,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 42,
                            DefenseTypingId = 7,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 43,
                            DefenseTypingId = 17,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 44,
                            DefenseTypingId = 18,
                            OffenseTypingId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 45,
                            DefenseTypingId = 6,
                            OffenseTypingId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 46,
                            DefenseTypingId = 7,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 47,
                            DefenseTypingId = 9,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 48,
                            DefenseTypingId = 11,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 49,
                            DefenseTypingId = 15,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 50,
                            DefenseTypingId = 5,
                            OffenseTypingId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 51,
                            DefenseTypingId = 4,
                            OffenseTypingId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 52,
                            DefenseTypingId = 14,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 53,
                            DefenseTypingId = 8,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 54,
                            DefenseTypingId = 6,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 55,
                            DefenseTypingId = 9,
                            OffenseTypingId = 8,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 56,
                            DefenseTypingId = 8,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 57,
                            DefenseTypingId = 2,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 58,
                            DefenseTypingId = 7,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 59,
                            DefenseTypingId = 11,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 60,
                            DefenseTypingId = 17,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 61,
                            DefenseTypingId = 13,
                            OffenseTypingId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 62,
                            DefenseTypingId = 6,
                            OffenseTypingId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 63,
                            DefenseTypingId = 5,
                            OffenseTypingId = 9,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 65,
                            DefenseTypingId = 7,
                            OffenseTypingId = 10,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 66,
                            DefenseTypingId = 10,
                            OffenseTypingId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 67,
                            DefenseTypingId = 17,
                            OffenseTypingId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 68,
                            DefenseTypingId = 16,
                            OffenseTypingId = 10,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 69,
                            DefenseTypingId = 13,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 70,
                            DefenseTypingId = 2,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 71,
                            DefenseTypingId = 5,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 72,
                            DefenseTypingId = 12,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 73,
                            DefenseTypingId = 3,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 74,
                            DefenseTypingId = 9,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 75,
                            DefenseTypingId = 17,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 76,
                            DefenseTypingId = 14,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 77,
                            DefenseTypingId = 5,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 78,
                            DefenseTypingId = 6,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 79,
                            DefenseTypingId = 9,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 80,
                            DefenseTypingId = 2,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 81,
                            DefenseTypingId = 12,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 82,
                            DefenseTypingId = 17,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 83,
                            DefenseTypingId = 4,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 84,
                            DefenseTypingId = 16,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 85,
                            DefenseTypingId = 6,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 86,
                            DefenseTypingId = 10,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 87,
                            DefenseTypingId = 18,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 88,
                            DefenseTypingId = 3,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 89,
                            DefenseTypingId = 2,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 90,
                            DefenseTypingId = 5,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 91,
                            DefenseTypingId = 15,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 92,
                            DefenseTypingId = 7,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 93,
                            DefenseTypingId = 17,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 94,
                            DefenseTypingId = 14,
                            OffenseTypingId = 14,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 95,
                            DefenseTypingId = 17,
                            OffenseTypingId = 14,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 96,
                            DefenseTypingId = 18,
                            OffenseTypingId = 14,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 97,
                            DefenseTypingId = 15,
                            OffenseTypingId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 98,
                            DefenseTypingId = 10,
                            OffenseTypingId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 99,
                            DefenseTypingId = 16,
                            OffenseTypingId = 15,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 100,
                            DefenseTypingId = 1,
                            OffenseTypingId = 15,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 101,
                            DefenseTypingId = 15,
                            OffenseTypingId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 102,
                            DefenseTypingId = 10,
                            OffenseTypingId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 103,
                            DefenseTypingId = 16,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 104,
                            DefenseTypingId = 18,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 105,
                            DefenseTypingId = 3,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 106,
                            DefenseTypingId = 18,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 107,
                            DefenseTypingId = 12,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 108,
                            DefenseTypingId = 11,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 109,
                            DefenseTypingId = 8,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 110,
                            DefenseTypingId = 2,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 111,
                            DefenseTypingId = 17,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 112,
                            DefenseTypingId = 4,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 113,
                            DefenseTypingId = 16,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 114,
                            DefenseTypingId = 14,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 115,
                            DefenseTypingId = 3,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 116,
                            DefenseTypingId = 2,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 117,
                            DefenseTypingId = 7,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 118,
                            DefenseTypingId = 17,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.Typing", b =>
                {
                    b.Property<int>("TypingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypingId");

                    b.ToTable("Typings");

                    b.HasData(
                        new
                        {
                            TypingId = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            TypingId = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            TypingId = 3,
                            Name = "Fighting"
                        },
                        new
                        {
                            TypingId = 4,
                            Name = "Water"
                        },
                        new
                        {
                            TypingId = 5,
                            Name = "Flying"
                        },
                        new
                        {
                            TypingId = 6,
                            Name = "Grass"
                        },
                        new
                        {
                            TypingId = 7,
                            Name = "Poison"
                        },
                        new
                        {
                            TypingId = 8,
                            Name = "Electric"
                        },
                        new
                        {
                            TypingId = 9,
                            Name = "Ground"
                        },
                        new
                        {
                            TypingId = 10,
                            Name = "Psychic"
                        },
                        new
                        {
                            TypingId = 11,
                            Name = "Rock"
                        },
                        new
                        {
                            TypingId = 12,
                            Name = "Ice"
                        },
                        new
                        {
                            TypingId = 13,
                            Name = "Bug"
                        },
                        new
                        {
                            TypingId = 14,
                            Name = "Dragon"
                        },
                        new
                        {
                            TypingId = 15,
                            Name = "Ghost"
                        },
                        new
                        {
                            TypingId = 16,
                            Name = "Dark"
                        },
                        new
                        {
                            TypingId = 17,
                            Name = "Steel"
                        },
                        new
                        {
                            TypingId = 18,
                            Name = "Fairy"
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonTyping", b =>
                {
                    b.HasOne("PokemonAPI.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonTypings")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Models.Typing", "Typing")
                        .WithMany("PokemonTypings")
                        .HasForeignKey("TypingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Typing");
                });

            modelBuilder.Entity("PokemonAPI.Models.TypeEffect", b =>
                {
                    b.HasOne("PokemonAPI.Models.Typing", "DefenseTyping")
                        .WithMany("TypeDefense")
                        .HasForeignKey("DefenseTypingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Models.Typing", "OffenseTyping")
                        .WithMany("TypeOffense")
                        .HasForeignKey("OffenseTypingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DefenseTyping");

                    b.Navigation("OffenseTyping");
                });

            modelBuilder.Entity("PokemonAPI.Models.Pokemon", b =>
                {
                    b.Navigation("PokemonTypings");
                });

            modelBuilder.Entity("PokemonAPI.Models.Typing", b =>
                {
                    b.Navigation("PokemonTypings");

                    b.Navigation("TypeDefense");

                    b.Navigation("TypeOffense");
                });
#pragma warning restore 612, 618
        }
    }
}
