// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonAPI.Data;

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20210406182612_extra pokemon seeding migration")]
    partial class extrapokemonseedingmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PokemonAPI.Models.Pokemon", b =>
                {
                    b.Property<int>("PokemonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EggGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokedexEntry")
                        .HasColumnType("int");

                    b.HasKey("PokemonId");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            Classification = "Sleeping Pokemon",
                            EggGroup = "Monster",
                            Generation = 1,
                            Name = "Snorlax",
                            PokedexEntry = 143
                        },
                        new
                        {
                            PokemonId = 2,
                            Classification = "Blocking Pokemon",
                            EggGroup = "Field",
                            Generation = 8,
                            Name = "Obstagoon",
                            PokedexEntry = 598
                        },
                        new
                        {
                            PokemonId = 3,
                            Classification = "Lizard Pokemon",
                            EggGroup = "Monster, Dragon",
                            Generation = 1,
                            Name = "Charmander",
                            PokedexEntry = 4
                        },
                        new
                        {
                            PokemonId = 4,
                            Classification = "Sun Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Volcarona",
                            PokedexEntry = 637
                        },
                        new
                        {
                            PokemonId = 5,
                            Classification = "Superpower Pokemon",
                            EggGroup = "Human-Like",
                            Generation = 1,
                            Name = "Machoke",
                            PokedexEntry = 67
                        },
                        new
                        {
                            PokemonId = 6,
                            Classification = "Single Horn Pokemon",
                            EggGroup = "Bug",
                            Generation = 2,
                            Name = "Heracross",
                            PokedexEntry = 214
                        },
                        new
                        {
                            PokemonId = 7,
                            Classification = "Mud Fish Pokemon",
                            EggGroup = "Monster, Water 1",
                            Generation = 3,
                            Name = "Swampert",
                            PokedexEntry = 260
                        },
                        new
                        {
                            PokemonId = 8,
                            Classification = "Mock Kelp Pokemon",
                            EggGroup = "Bug",
                            Generation = 6,
                            Name = "Skrelp",
                            PokedexEntry = 637
                        },
                        new
                        {
                            PokemonId = 9,
                            Classification = "Raven Pokemon",
                            EggGroup = "Flying",
                            Generation = 8,
                            Name = "Corviknight",
                            PokedexEntry = 823
                        },
                        new
                        {
                            PokemonId = 10,
                            Classification = "Balloon Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 4,
                            Name = "Drifloon",
                            PokedexEntry = 425
                        },
                        new
                        {
                            PokemonId = 11,
                            Classification = "Sickle Grass Pokemon",
                            EggGroup = "Grass",
                            Generation = 7,
                            Name = "Fomantis",
                            PokedexEntry = 753
                        },
                        new
                        {
                            PokemonId = 12,
                            Classification = "Sea Lily Pokemon",
                            EggGroup = "Water 3",
                            Generation = 3,
                            Name = "Lileep",
                            PokedexEntry = 345
                        },
                        new
                        {
                            PokemonId = 13,
                            Classification = "Poison Pin Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 7,
                            Name = "Naganadel",
                            PokedexEntry = 804
                        },
                        new
                        {
                            PokemonId = 14,
                            Classification = "Bouquet Pokemon",
                            EggGroup = "Fairy, Grass",
                            Generation = 4,
                            Name = "Roserade",
                            PokedexEntry = 407
                        },
                        new
                        {
                            PokemonId = 15,
                            Classification = "Magnet Area Pokemon",
                            EggGroup = "Mineral",
                            Generation = 4,
                            Name = "Magnezone",
                            PokedexEntry = 462
                        },
                        new
                        {
                            PokemonId = 16,
                            Classification = "Deep Black Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 5,
                            Name = "Zekrom",
                            PokedexEntry = 644
                        },
                        new
                        {
                            PokemonId = 17,
                            Classification = "Automaton Pokemon",
                            EggGroup = "Mineral",
                            Generation = 5,
                            Name = "Golett",
                            PokedexEntry = 622
                        },
                        new
                        {
                            PokemonId = 18,
                            Classification = "Order Pokemon",
                            EggGroup = "Undiscovered",
                            Generation = 6,
                            Name = "Zygarde",
                            PokedexEntry = 718
                        },
                        new
                        {
                            PokemonId = 19,
                            Classification = "Psi Pokemon",
                            EggGroup = "Human-Like",
                            Generation = 1,
                            Name = "Abra",
                            PokedexEntry = 63
                        },
                        new
                        {
                            PokemonId = 20,
                            Classification = "Bronze Bell Pokemon",
                            EggGroup = "Mineral",
                            Generation = 4,
                            Name = "Bronzong",
                            PokedexEntry = 437
                        },
                        new
                        {
                            PokemonId = 21,
                            Classification = "Head Butt Pokemon",
                            EggGroup = "Monster",
                            Generation = 4,
                            Name = "Rampardos",
                            PokedexEntry = 409
                        },
                        new
                        {
                            PokemonId = 22,
                            Classification = "Tundra Pokemon",
                            EggGroup = "Monster",
                            Generation = 6,
                            Name = "Aurorus",
                            PokedexEntry = 699
                        },
                        new
                        {
                            PokemonId = 23,
                            Classification = "Snow Hat Pokemon",
                            EggGroup = "Fairy, Mineral",
                            Generation = 3,
                            Name = "Snorunt",
                            PokedexEntry = 361
                        },
                        new
                        {
                            PokemonId = 24,
                            Classification = "Worm Pokemon",
                            EggGroup = "Bug",
                            Generation = 8,
                            Name = "Snom",
                            PokedexEntry = 872
                        },
                        new
                        {
                            PokemonId = 25,
                            Classification = "Leaf-Wrapped Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Swadloon",
                            PokedexEntry = 541
                        },
                        new
                        {
                            PokemonId = 26,
                            Classification = "Curlipede Pokemon",
                            EggGroup = "Bug",
                            Generation = 5,
                            Name = "Whirlipede",
                            PokedexEntry = 544
                        },
                        new
                        {
                            PokemonId = 27,
                            Classification = "Dragon Pokemon",
                            EggGroup = "Water 1, Dragon",
                            Generation = 1,
                            Name = "Dragonair",
                            PokedexEntry = 148
                        },
                        new
                        {
                            PokemonId = 28,
                            Classification = "Stealth Pokemon",
                            EggGroup = "Amorphous, Dragon",
                            Generation = 8,
                            Name = "Dragapult",
                            PokedexEntry = 887
                        },
                        new
                        {
                            PokemonId = 29,
                            Classification = "Screech Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 2,
                            Name = "Misdreavus",
                            PokedexEntry = 200
                        },
                        new
                        {
                            PokemonId = 30,
                            Classification = "Magical Pokemon",
                            EggGroup = "Amorphous",
                            Generation = 4,
                            Name = "Mismagius",
                            PokedexEntry = 429
                        },
                        new
                        {
                            PokemonId = 31,
                            Classification = "Wily Pokemon",
                            EggGroup = "Field, Grass",
                            Generation = 3,
                            Name = "Nuzleaf",
                            PokedexEntry = 306
                        },
                        new
                        {
                            PokemonId = 32,
                            Classification = "Skunk Pokemon",
                            EggGroup = "Field",
                            Generation = 4,
                            Name = "Skuntank",
                            PokedexEntry = 435
                        },
                        new
                        {
                            PokemonId = 33,
                            Classification = "Iron Armor Pokemon",
                            EggGroup = "Monster",
                            Generation = 3,
                            Name = "Aggron",
                            PokedexEntry = 306
                        },
                        new
                        {
                            PokemonId = 34,
                            Classification = "Thorn Pod Pokemon",
                            EggGroup = "Grass, Mineral",
                            Generation = 5,
                            Name = "Ferrothorn",
                            PokedexEntry = 598
                        },
                        new
                        {
                            PokemonId = 35,
                            Classification = "Balloon Pokemon",
                            EggGroup = "Fairy",
                            Generation = 1,
                            Name = "Jigglypuff",
                            PokedexEntry = 39
                        },
                        new
                        {
                            PokemonId = 36,
                            Classification = "Embrace Pokemon",
                            EggGroup = "Human-Like, Amorphous",
                            Generation = 3,
                            Name = "Gardevoir",
                            PokedexEntry = 282
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonTyping", b =>
                {
                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("TypingId")
                        .HasColumnType("int");

                    b.HasKey("PokemonId", "TypingId");

                    b.HasIndex("TypingId");

                    b.ToTable("PokemonTyping");

                    b.HasData(
                        new
                        {
                            PokemonId = 1,
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = 2,
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = 2,
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = 3,
                            TypingId = 2
                        },
                        new
                        {
                            PokemonId = 4,
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = 4,
                            TypingId = 2
                        },
                        new
                        {
                            PokemonId = 5,
                            TypingId = 3
                        },
                        new
                        {
                            PokemonId = 6,
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = 6,
                            TypingId = 3
                        },
                        new
                        {
                            PokemonId = 7,
                            TypingId = 4
                        },
                        new
                        {
                            PokemonId = 7,
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = 8,
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = 8,
                            TypingId = 4
                        },
                        new
                        {
                            PokemonId = 9,
                            TypingId = 5
                        },
                        new
                        {
                            PokemonId = 9,
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = 10,
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = 10,
                            TypingId = 5
                        },
                        new
                        {
                            PokemonId = 11,
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = 12,
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = 12,
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = 13,
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = 13,
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = 14,
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = 14,
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = 15,
                            TypingId = 8
                        },
                        new
                        {
                            PokemonId = 15,
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = 16,
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = 16,
                            TypingId = 8
                        },
                        new
                        {
                            PokemonId = 17,
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = 17,
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = 18,
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = 18,
                            TypingId = 9
                        },
                        new
                        {
                            PokemonId = 19,
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = 20,
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = 20,
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = 21,
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = 22,
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = 22,
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = 23,
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = 24,
                            TypingId = 12
                        },
                        new
                        {
                            PokemonId = 24,
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = 25,
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = 25,
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = 26,
                            TypingId = 13
                        },
                        new
                        {
                            PokemonId = 26,
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = 27,
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = 28,
                            TypingId = 14
                        },
                        new
                        {
                            PokemonId = 28,
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = 29,
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = 30,
                            TypingId = 15
                        },
                        new
                        {
                            PokemonId = 31,
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = 31,
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = 32,
                            TypingId = 7
                        },
                        new
                        {
                            PokemonId = 32,
                            TypingId = 16
                        },
                        new
                        {
                            PokemonId = 33,
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = 33,
                            TypingId = 11
                        },
                        new
                        {
                            PokemonId = 34,
                            TypingId = 6
                        },
                        new
                        {
                            PokemonId = 34,
                            TypingId = 17
                        },
                        new
                        {
                            PokemonId = 35,
                            TypingId = 1
                        },
                        new
                        {
                            PokemonId = 35,
                            TypingId = 18
                        },
                        new
                        {
                            PokemonId = 36,
                            TypingId = 10
                        },
                        new
                        {
                            PokemonId = 36,
                            TypingId = 18
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.TypeEffect", b =>
                {
                    b.Property<int>("TypeEffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DefenseTypingId")
                        .HasColumnType("int");

                    b.Property<int>("OffenseTypingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TypeEffectId");

                    b.HasIndex("DefenseTypingId");

                    b.HasIndex("OffenseTypingId");

                    b.ToTable("TypeEffects");

                    b.HasData(
                        new
                        {
                            TypeEffectId = 1,
                            DefenseTypingId = 11,
                            OffenseTypingId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 2,
                            DefenseTypingId = 17,
                            OffenseTypingId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 3,
                            DefenseTypingId = 15,
                            OffenseTypingId = 1,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 4,
                            DefenseTypingId = 13,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 5,
                            DefenseTypingId = 6,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 6,
                            DefenseTypingId = 12,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 7,
                            DefenseTypingId = 14,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 8,
                            DefenseTypingId = 2,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 9,
                            DefenseTypingId = 11,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 10,
                            DefenseTypingId = 4,
                            OffenseTypingId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 11,
                            DefenseTypingId = 16,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 12,
                            DefenseTypingId = 12,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 13,
                            DefenseTypingId = 1,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 14,
                            DefenseTypingId = 11,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 15,
                            DefenseTypingId = 17,
                            OffenseTypingId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 16,
                            DefenseTypingId = 13,
                            OffenseTypingId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 17,
                            DefenseTypingId = 18,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 18,
                            DefenseTypingId = 5,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 19,
                            DefenseTypingId = 7,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 20,
                            DefenseTypingId = 10,
                            OffenseTypingId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 21,
                            DefenseTypingId = 15,
                            OffenseTypingId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 22,
                            DefenseTypingId = 2,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 23,
                            DefenseTypingId = 9,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 24,
                            DefenseTypingId = 11,
                            OffenseTypingId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 25,
                            DefenseTypingId = 14,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 26,
                            DefenseTypingId = 6,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 27,
                            DefenseTypingId = 4,
                            OffenseTypingId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 28,
                            DefenseTypingId = 13,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 29,
                            DefenseTypingId = 3,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 30,
                            DefenseTypingId = 6,
                            OffenseTypingId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 31,
                            DefenseTypingId = 8,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 32,
                            DefenseTypingId = 11,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 33,
                            DefenseTypingId = 17,
                            OffenseTypingId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 34,
                            DefenseTypingId = 9,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 35,
                            DefenseTypingId = 11,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 36,
                            DefenseTypingId = 4,
                            OffenseTypingId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 37,
                            DefenseTypingId = 13,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 38,
                            DefenseTypingId = 14,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 39,
                            DefenseTypingId = 2,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 40,
                            DefenseTypingId = 5,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 41,
                            DefenseTypingId = 6,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 42,
                            DefenseTypingId = 7,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 43,
                            DefenseTypingId = 17,
                            OffenseTypingId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 44,
                            DefenseTypingId = 18,
                            OffenseTypingId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 45,
                            DefenseTypingId = 6,
                            OffenseTypingId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 46,
                            DefenseTypingId = 7,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 47,
                            DefenseTypingId = 9,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 48,
                            DefenseTypingId = 11,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 49,
                            DefenseTypingId = 15,
                            OffenseTypingId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 50,
                            DefenseTypingId = 5,
                            OffenseTypingId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 51,
                            DefenseTypingId = 4,
                            OffenseTypingId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 52,
                            DefenseTypingId = 14,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 53,
                            DefenseTypingId = 8,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 54,
                            DefenseTypingId = 6,
                            OffenseTypingId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 55,
                            DefenseTypingId = 9,
                            OffenseTypingId = 8,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 56,
                            DefenseTypingId = 8,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 57,
                            DefenseTypingId = 2,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 58,
                            DefenseTypingId = 7,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 59,
                            DefenseTypingId = 11,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 60,
                            DefenseTypingId = 17,
                            OffenseTypingId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 61,
                            DefenseTypingId = 13,
                            OffenseTypingId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 62,
                            DefenseTypingId = 6,
                            OffenseTypingId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 63,
                            DefenseTypingId = 5,
                            OffenseTypingId = 9,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 65,
                            DefenseTypingId = 7,
                            OffenseTypingId = 10,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 66,
                            DefenseTypingId = 10,
                            OffenseTypingId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 67,
                            DefenseTypingId = 17,
                            OffenseTypingId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 68,
                            DefenseTypingId = 16,
                            OffenseTypingId = 10,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 69,
                            DefenseTypingId = 13,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 70,
                            DefenseTypingId = 2,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 71,
                            DefenseTypingId = 5,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 72,
                            DefenseTypingId = 12,
                            OffenseTypingId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 73,
                            DefenseTypingId = 3,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 74,
                            DefenseTypingId = 9,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 75,
                            DefenseTypingId = 17,
                            OffenseTypingId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 76,
                            DefenseTypingId = 14,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 77,
                            DefenseTypingId = 5,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 78,
                            DefenseTypingId = 6,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 79,
                            DefenseTypingId = 9,
                            OffenseTypingId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 80,
                            DefenseTypingId = 2,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 81,
                            DefenseTypingId = 12,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 82,
                            DefenseTypingId = 17,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 83,
                            DefenseTypingId = 4,
                            OffenseTypingId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 84,
                            DefenseTypingId = 16,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 85,
                            DefenseTypingId = 6,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 86,
                            DefenseTypingId = 10,
                            OffenseTypingId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 87,
                            DefenseTypingId = 18,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 88,
                            DefenseTypingId = 3,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 89,
                            DefenseTypingId = 2,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 90,
                            DefenseTypingId = 5,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 91,
                            DefenseTypingId = 15,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 92,
                            DefenseTypingId = 7,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 93,
                            DefenseTypingId = 17,
                            OffenseTypingId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 94,
                            DefenseTypingId = 14,
                            OffenseTypingId = 14,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 95,
                            DefenseTypingId = 17,
                            OffenseTypingId = 14,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 96,
                            DefenseTypingId = 18,
                            OffenseTypingId = 14,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 97,
                            DefenseTypingId = 15,
                            OffenseTypingId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 98,
                            DefenseTypingId = 10,
                            OffenseTypingId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 99,
                            DefenseTypingId = 16,
                            OffenseTypingId = 15,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 100,
                            DefenseTypingId = 1,
                            OffenseTypingId = 15,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 101,
                            DefenseTypingId = 15,
                            OffenseTypingId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 102,
                            DefenseTypingId = 10,
                            OffenseTypingId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 103,
                            DefenseTypingId = 16,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 104,
                            DefenseTypingId = 18,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 105,
                            DefenseTypingId = 3,
                            OffenseTypingId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 106,
                            DefenseTypingId = 18,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 107,
                            DefenseTypingId = 12,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 108,
                            DefenseTypingId = 11,
                            OffenseTypingId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 109,
                            DefenseTypingId = 8,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 110,
                            DefenseTypingId = 2,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 111,
                            DefenseTypingId = 17,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 112,
                            DefenseTypingId = 4,
                            OffenseTypingId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 113,
                            DefenseTypingId = 16,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 114,
                            DefenseTypingId = 14,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 115,
                            DefenseTypingId = 3,
                            OffenseTypingId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 116,
                            DefenseTypingId = 2,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 117,
                            DefenseTypingId = 7,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 118,
                            DefenseTypingId = 17,
                            OffenseTypingId = 18,
                            Power = 0.5m
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.Typing", b =>
                {
                    b.Property<int>("TypingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypingId");

                    b.ToTable("Typings");

                    b.HasData(
                        new
                        {
                            TypingId = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            TypingId = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            TypingId = 3,
                            Name = "Fighting"
                        },
                        new
                        {
                            TypingId = 4,
                            Name = "Water"
                        },
                        new
                        {
                            TypingId = 5,
                            Name = "Flying"
                        },
                        new
                        {
                            TypingId = 6,
                            Name = "Grass"
                        },
                        new
                        {
                            TypingId = 7,
                            Name = "Poison"
                        },
                        new
                        {
                            TypingId = 8,
                            Name = "Electric"
                        },
                        new
                        {
                            TypingId = 9,
                            Name = "Ground"
                        },
                        new
                        {
                            TypingId = 10,
                            Name = "Psychic"
                        },
                        new
                        {
                            TypingId = 11,
                            Name = "Rock"
                        },
                        new
                        {
                            TypingId = 12,
                            Name = "Ice"
                        },
                        new
                        {
                            TypingId = 13,
                            Name = "Bug"
                        },
                        new
                        {
                            TypingId = 14,
                            Name = "Dragon"
                        },
                        new
                        {
                            TypingId = 15,
                            Name = "Ghost"
                        },
                        new
                        {
                            TypingId = 16,
                            Name = "Dark"
                        },
                        new
                        {
                            TypingId = 17,
                            Name = "Steel"
                        },
                        new
                        {
                            TypingId = 18,
                            Name = "Fairy"
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonTyping", b =>
                {
                    b.HasOne("PokemonAPI.Models.Pokemon", "Pokemon")
                        .WithMany("PokemonTypings")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Models.Typing", "Typing")
                        .WithMany("PokemonTypings")
                        .HasForeignKey("TypingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("Typing");
                });

            modelBuilder.Entity("PokemonAPI.Models.TypeEffect", b =>
                {
                    b.HasOne("PokemonAPI.Models.Typing", "DefenseTyping")
                        .WithMany("TypeDefense")
                        .HasForeignKey("DefenseTypingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Models.Typing", "OffenseTyping")
                        .WithMany("TypeOffense")
                        .HasForeignKey("OffenseTypingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DefenseTyping");

                    b.Navigation("OffenseTyping");
                });

            modelBuilder.Entity("PokemonAPI.Models.Pokemon", b =>
                {
                    b.Navigation("PokemonTypings");
                });

            modelBuilder.Entity("PokemonAPI.Models.Typing", b =>
                {
                    b.Navigation("PokemonTypings");

                    b.Navigation("TypeDefense");

                    b.Navigation("TypeOffense");
                });
#pragma warning restore 612, 618
        }
    }
}
