// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonAPI.Data;

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(PokemonContext))]
    partial class PokemonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PokemonAPI.Models.PokemonType", b =>
                {
                    b.Property<int>("PokemonTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PokemonTypeId");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            PokemonTypeId = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            PokemonTypeId = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            PokemonTypeId = 3,
                            Name = "Fighting"
                        },
                        new
                        {
                            PokemonTypeId = 4,
                            Name = "Water"
                        },
                        new
                        {
                            PokemonTypeId = 5,
                            Name = "Flying"
                        },
                        new
                        {
                            PokemonTypeId = 6,
                            Name = "Grass"
                        },
                        new
                        {
                            PokemonTypeId = 7,
                            Name = "Poison"
                        },
                        new
                        {
                            PokemonTypeId = 8,
                            Name = "Electric"
                        },
                        new
                        {
                            PokemonTypeId = 9,
                            Name = "Ground"
                        },
                        new
                        {
                            PokemonTypeId = 10,
                            Name = "Psychic"
                        },
                        new
                        {
                            PokemonTypeId = 11,
                            Name = "Rock"
                        },
                        new
                        {
                            PokemonTypeId = 12,
                            Name = "Ice"
                        },
                        new
                        {
                            PokemonTypeId = 13,
                            Name = "Bug"
                        },
                        new
                        {
                            PokemonTypeId = 14,
                            Name = "Dragon"
                        },
                        new
                        {
                            PokemonTypeId = 15,
                            Name = "Ghost"
                        },
                        new
                        {
                            PokemonTypeId = 16,
                            Name = "Dark"
                        },
                        new
                        {
                            PokemonTypeId = 17,
                            Name = "Steel"
                        },
                        new
                        {
                            PokemonTypeId = 18,
                            Name = "Fairy"
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.TypeEffect", b =>
                {
                    b.Property<int>("UserPokemonTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TargetPokemonTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserPokemonTypeId", "TargetPokemonTypeId");

                    b.HasIndex("TargetPokemonTypeId");

                    b.ToTable("TypeEffects");

                    b.HasData(
                        new
                        {
                            UserPokemonTypeId = 1,
                            TargetPokemonTypeId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 1,
                            TargetPokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 1,
                            TargetPokemonTypeId = 15,
                            Power = 0m
                        },
                        new
                        {
                            UserPokemonTypeId = 2,
                            TargetPokemonTypeId = 13,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 2,
                            TargetPokemonTypeId = 6,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 2,
                            TargetPokemonTypeId = 12,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 2,
                            TargetPokemonTypeId = 14,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 2,
                            TargetPokemonTypeId = 2,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 2,
                            TargetPokemonTypeId = 11,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 2,
                            TargetPokemonTypeId = 4,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 3,
                            TargetPokemonTypeId = 16,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 3,
                            TargetPokemonTypeId = 12,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 3,
                            TargetPokemonTypeId = 1,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 3,
                            TargetPokemonTypeId = 11,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 3,
                            TargetPokemonTypeId = 17,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 3,
                            TargetPokemonTypeId = 13,
                            Power = 0m
                        },
                        new
                        {
                            UserPokemonTypeId = 3,
                            TargetPokemonTypeId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 3,
                            TargetPokemonTypeId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 3,
                            TargetPokemonTypeId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 3,
                            TargetPokemonTypeId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 3,
                            TargetPokemonTypeId = 15,
                            Power = 0m
                        },
                        new
                        {
                            UserPokemonTypeId = 4,
                            TargetPokemonTypeId = 2,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 4,
                            TargetPokemonTypeId = 9,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 4,
                            TargetPokemonTypeId = 11,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 4,
                            TargetPokemonTypeId = 14,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 4,
                            TargetPokemonTypeId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 4,
                            TargetPokemonTypeId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 5,
                            TargetPokemonTypeId = 13,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 5,
                            TargetPokemonTypeId = 3,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 5,
                            TargetPokemonTypeId = 6,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 5,
                            TargetPokemonTypeId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 5,
                            TargetPokemonTypeId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 5,
                            TargetPokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 6,
                            TargetPokemonTypeId = 9,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 6,
                            TargetPokemonTypeId = 11,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 6,
                            TargetPokemonTypeId = 4,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 6,
                            TargetPokemonTypeId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 6,
                            TargetPokemonTypeId = 14,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 6,
                            TargetPokemonTypeId = 2,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 6,
                            TargetPokemonTypeId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 6,
                            TargetPokemonTypeId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 6,
                            TargetPokemonTypeId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 6,
                            TargetPokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 7,
                            TargetPokemonTypeId = 18,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 7,
                            TargetPokemonTypeId = 6,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 7,
                            TargetPokemonTypeId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 7,
                            TargetPokemonTypeId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 7,
                            TargetPokemonTypeId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 7,
                            TargetPokemonTypeId = 15,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 8,
                            TargetPokemonTypeId = 5,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 8,
                            TargetPokemonTypeId = 4,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 8,
                            TargetPokemonTypeId = 14,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 8,
                            TargetPokemonTypeId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 8,
                            TargetPokemonTypeId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 8,
                            TargetPokemonTypeId = 9,
                            Power = 0m
                        },
                        new
                        {
                            UserPokemonTypeId = 9,
                            TargetPokemonTypeId = 8,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 9,
                            TargetPokemonTypeId = 2,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 9,
                            TargetPokemonTypeId = 7,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 9,
                            TargetPokemonTypeId = 11,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 9,
                            TargetPokemonTypeId = 17,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 9,
                            TargetPokemonTypeId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 9,
                            TargetPokemonTypeId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 9,
                            TargetPokemonTypeId = 5,
                            Power = 0m
                        },
                        new
                        {
                            UserPokemonTypeId = 10,
                            TargetPokemonTypeId = 7,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 10,
                            TargetPokemonTypeId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 10,
                            TargetPokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 10,
                            TargetPokemonTypeId = 16,
                            Power = 0m
                        },
                        new
                        {
                            UserPokemonTypeId = 11,
                            TargetPokemonTypeId = 13,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 11,
                            TargetPokemonTypeId = 2,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 11,
                            TargetPokemonTypeId = 5,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 11,
                            TargetPokemonTypeId = 12,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 11,
                            TargetPokemonTypeId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 11,
                            TargetPokemonTypeId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 11,
                            TargetPokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 12,
                            TargetPokemonTypeId = 14,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 12,
                            TargetPokemonTypeId = 5,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 12,
                            TargetPokemonTypeId = 6,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 12,
                            TargetPokemonTypeId = 9,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 12,
                            TargetPokemonTypeId = 2,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 12,
                            TargetPokemonTypeId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 12,
                            TargetPokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 12,
                            TargetPokemonTypeId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 13,
                            TargetPokemonTypeId = 16,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 13,
                            TargetPokemonTypeId = 6,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 13,
                            TargetPokemonTypeId = 10,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 13,
                            TargetPokemonTypeId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 13,
                            TargetPokemonTypeId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 13,
                            TargetPokemonTypeId = 2,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 13,
                            TargetPokemonTypeId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 13,
                            TargetPokemonTypeId = 15,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 13,
                            TargetPokemonTypeId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 13,
                            TargetPokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 14,
                            TargetPokemonTypeId = 14,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 14,
                            TargetPokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 14,
                            TargetPokemonTypeId = 18,
                            Power = 0m
                        },
                        new
                        {
                            UserPokemonTypeId = 15,
                            TargetPokemonTypeId = 15,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 15,
                            TargetPokemonTypeId = 10,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 15,
                            TargetPokemonTypeId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 15,
                            TargetPokemonTypeId = 1,
                            Power = 0m
                        },
                        new
                        {
                            UserPokemonTypeId = 16,
                            TargetPokemonTypeId = 15,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 16,
                            TargetPokemonTypeId = 10,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 16,
                            TargetPokemonTypeId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 16,
                            TargetPokemonTypeId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 16,
                            TargetPokemonTypeId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 17,
                            TargetPokemonTypeId = 18,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 17,
                            TargetPokemonTypeId = 12,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 17,
                            TargetPokemonTypeId = 11,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 17,
                            TargetPokemonTypeId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 17,
                            TargetPokemonTypeId = 2,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 17,
                            TargetPokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 17,
                            TargetPokemonTypeId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 18,
                            TargetPokemonTypeId = 16,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 18,
                            TargetPokemonTypeId = 14,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 18,
                            TargetPokemonTypeId = 3,
                            Power = 2m
                        },
                        new
                        {
                            UserPokemonTypeId = 18,
                            TargetPokemonTypeId = 2,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 18,
                            TargetPokemonTypeId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            UserPokemonTypeId = 18,
                            TargetPokemonTypeId = 17,
                            Power = 0.5m
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.TypeEffect", b =>
                {
                    b.HasOne("PokemonAPI.Models.PokemonType", "TargetPokemonType")
                        .WithMany("TypeEffects")
                        .HasForeignKey("TargetPokemonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetPokemonType");
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonType", b =>
                {
                    b.Navigation("TypeEffects");
                });
#pragma warning restore 612, 618
        }
    }
}
