// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonAPI.Data;

namespace PokemonAPI.Migrations
{
    [DbContext(typeof(PokemonContext))]
    partial class PokemonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PokemonAPI.Models.PokemonType", b =>
                {
                    b.Property<int>("PokemonTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PokemonTypeId");

                    b.ToTable("PokemonTypes");

                    b.HasData(
                        new
                        {
                            PokemonTypeId = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            PokemonTypeId = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            PokemonTypeId = 3,
                            Name = "Fighting"
                        },
                        new
                        {
                            PokemonTypeId = 4,
                            Name = "Water"
                        },
                        new
                        {
                            PokemonTypeId = 5,
                            Name = "Flying"
                        },
                        new
                        {
                            PokemonTypeId = 6,
                            Name = "Grass"
                        },
                        new
                        {
                            PokemonTypeId = 7,
                            Name = "Poison"
                        },
                        new
                        {
                            PokemonTypeId = 8,
                            Name = "Electric"
                        },
                        new
                        {
                            PokemonTypeId = 9,
                            Name = "Ground"
                        },
                        new
                        {
                            PokemonTypeId = 10,
                            Name = "Psychic"
                        },
                        new
                        {
                            PokemonTypeId = 11,
                            Name = "Rock"
                        },
                        new
                        {
                            PokemonTypeId = 12,
                            Name = "Ice"
                        },
                        new
                        {
                            PokemonTypeId = 13,
                            Name = "Bug"
                        },
                        new
                        {
                            PokemonTypeId = 14,
                            Name = "Dragon"
                        },
                        new
                        {
                            PokemonTypeId = 15,
                            Name = "Ghost"
                        },
                        new
                        {
                            PokemonTypeId = 16,
                            Name = "Dark"
                        },
                        new
                        {
                            PokemonTypeId = 17,
                            Name = "Steel"
                        },
                        new
                        {
                            PokemonTypeId = 18,
                            Name = "Fairy"
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.TypeEffect", b =>
                {
                    b.Property<int>("TypeEffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DefensePokemonTypeId")
                        .HasColumnType("int");

                    b.Property<int>("OffensePokemonTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Power")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TypeEffectId");

                    b.HasIndex("DefensePokemonTypeId");

                    b.HasIndex("OffensePokemonTypeId");

                    b.ToTable("TypeEffects");

                    b.HasData(
                        new
                        {
                            TypeEffectId = 1,
                            DefensePokemonTypeId = 11,
                            OffensePokemonTypeId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 2,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 1,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 3,
                            DefensePokemonTypeId = 15,
                            OffensePokemonTypeId = 1,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 4,
                            DefensePokemonTypeId = 13,
                            OffensePokemonTypeId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 5,
                            DefensePokemonTypeId = 6,
                            OffensePokemonTypeId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 6,
                            DefensePokemonTypeId = 12,
                            OffensePokemonTypeId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 7,
                            DefensePokemonTypeId = 14,
                            OffensePokemonTypeId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 8,
                            DefensePokemonTypeId = 2,
                            OffensePokemonTypeId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 9,
                            DefensePokemonTypeId = 11,
                            OffensePokemonTypeId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 10,
                            DefensePokemonTypeId = 4,
                            OffensePokemonTypeId = 2,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 11,
                            DefensePokemonTypeId = 16,
                            OffensePokemonTypeId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 12,
                            DefensePokemonTypeId = 12,
                            OffensePokemonTypeId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 13,
                            DefensePokemonTypeId = 1,
                            OffensePokemonTypeId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 14,
                            DefensePokemonTypeId = 11,
                            OffensePokemonTypeId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 15,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 3,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 16,
                            DefensePokemonTypeId = 13,
                            OffensePokemonTypeId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 17,
                            DefensePokemonTypeId = 18,
                            OffensePokemonTypeId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 18,
                            DefensePokemonTypeId = 5,
                            OffensePokemonTypeId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 19,
                            DefensePokemonTypeId = 7,
                            OffensePokemonTypeId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 20,
                            DefensePokemonTypeId = 10,
                            OffensePokemonTypeId = 3,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 21,
                            DefensePokemonTypeId = 15,
                            OffensePokemonTypeId = 3,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 22,
                            DefensePokemonTypeId = 2,
                            OffensePokemonTypeId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 23,
                            DefensePokemonTypeId = 9,
                            OffensePokemonTypeId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 24,
                            DefensePokemonTypeId = 11,
                            OffensePokemonTypeId = 4,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 25,
                            DefensePokemonTypeId = 14,
                            OffensePokemonTypeId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 26,
                            DefensePokemonTypeId = 6,
                            OffensePokemonTypeId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 27,
                            DefensePokemonTypeId = 4,
                            OffensePokemonTypeId = 4,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 28,
                            DefensePokemonTypeId = 13,
                            OffensePokemonTypeId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 29,
                            DefensePokemonTypeId = 3,
                            OffensePokemonTypeId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 30,
                            DefensePokemonTypeId = 6,
                            OffensePokemonTypeId = 5,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 31,
                            DefensePokemonTypeId = 8,
                            OffensePokemonTypeId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 32,
                            DefensePokemonTypeId = 11,
                            OffensePokemonTypeId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 33,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 5,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 34,
                            DefensePokemonTypeId = 9,
                            OffensePokemonTypeId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 35,
                            DefensePokemonTypeId = 11,
                            OffensePokemonTypeId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 36,
                            DefensePokemonTypeId = 4,
                            OffensePokemonTypeId = 6,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 37,
                            DefensePokemonTypeId = 13,
                            OffensePokemonTypeId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 38,
                            DefensePokemonTypeId = 14,
                            OffensePokemonTypeId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 39,
                            DefensePokemonTypeId = 2,
                            OffensePokemonTypeId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 40,
                            DefensePokemonTypeId = 5,
                            OffensePokemonTypeId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 41,
                            DefensePokemonTypeId = 6,
                            OffensePokemonTypeId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 42,
                            DefensePokemonTypeId = 7,
                            OffensePokemonTypeId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 43,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 6,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 44,
                            DefensePokemonTypeId = 18,
                            OffensePokemonTypeId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 45,
                            DefensePokemonTypeId = 6,
                            OffensePokemonTypeId = 7,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 46,
                            DefensePokemonTypeId = 7,
                            OffensePokemonTypeId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 47,
                            DefensePokemonTypeId = 9,
                            OffensePokemonTypeId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 48,
                            DefensePokemonTypeId = 11,
                            OffensePokemonTypeId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 49,
                            DefensePokemonTypeId = 15,
                            OffensePokemonTypeId = 7,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 50,
                            DefensePokemonTypeId = 5,
                            OffensePokemonTypeId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 51,
                            DefensePokemonTypeId = 4,
                            OffensePokemonTypeId = 8,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 52,
                            DefensePokemonTypeId = 14,
                            OffensePokemonTypeId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 53,
                            DefensePokemonTypeId = 8,
                            OffensePokemonTypeId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 54,
                            DefensePokemonTypeId = 6,
                            OffensePokemonTypeId = 8,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 55,
                            DefensePokemonTypeId = 9,
                            OffensePokemonTypeId = 8,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 56,
                            DefensePokemonTypeId = 8,
                            OffensePokemonTypeId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 57,
                            DefensePokemonTypeId = 2,
                            OffensePokemonTypeId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 58,
                            DefensePokemonTypeId = 7,
                            OffensePokemonTypeId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 59,
                            DefensePokemonTypeId = 11,
                            OffensePokemonTypeId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 60,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 9,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 61,
                            DefensePokemonTypeId = 13,
                            OffensePokemonTypeId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 62,
                            DefensePokemonTypeId = 6,
                            OffensePokemonTypeId = 9,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 63,
                            DefensePokemonTypeId = 5,
                            OffensePokemonTypeId = 9,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 65,
                            DefensePokemonTypeId = 7,
                            OffensePokemonTypeId = 10,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 66,
                            DefensePokemonTypeId = 10,
                            OffensePokemonTypeId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 67,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 10,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 68,
                            DefensePokemonTypeId = 16,
                            OffensePokemonTypeId = 10,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 69,
                            DefensePokemonTypeId = 13,
                            OffensePokemonTypeId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 70,
                            DefensePokemonTypeId = 2,
                            OffensePokemonTypeId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 71,
                            DefensePokemonTypeId = 5,
                            OffensePokemonTypeId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 72,
                            DefensePokemonTypeId = 12,
                            OffensePokemonTypeId = 11,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 73,
                            DefensePokemonTypeId = 3,
                            OffensePokemonTypeId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 74,
                            DefensePokemonTypeId = 9,
                            OffensePokemonTypeId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 75,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 11,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 76,
                            DefensePokemonTypeId = 14,
                            OffensePokemonTypeId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 77,
                            DefensePokemonTypeId = 5,
                            OffensePokemonTypeId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 78,
                            DefensePokemonTypeId = 6,
                            OffensePokemonTypeId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 79,
                            DefensePokemonTypeId = 9,
                            OffensePokemonTypeId = 12,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 80,
                            DefensePokemonTypeId = 2,
                            OffensePokemonTypeId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 81,
                            DefensePokemonTypeId = 12,
                            OffensePokemonTypeId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 82,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 83,
                            DefensePokemonTypeId = 4,
                            OffensePokemonTypeId = 12,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 84,
                            DefensePokemonTypeId = 16,
                            OffensePokemonTypeId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 85,
                            DefensePokemonTypeId = 6,
                            OffensePokemonTypeId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 86,
                            DefensePokemonTypeId = 10,
                            OffensePokemonTypeId = 13,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 87,
                            DefensePokemonTypeId = 18,
                            OffensePokemonTypeId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 88,
                            DefensePokemonTypeId = 3,
                            OffensePokemonTypeId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 89,
                            DefensePokemonTypeId = 2,
                            OffensePokemonTypeId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 90,
                            DefensePokemonTypeId = 5,
                            OffensePokemonTypeId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 91,
                            DefensePokemonTypeId = 15,
                            OffensePokemonTypeId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 92,
                            DefensePokemonTypeId = 7,
                            OffensePokemonTypeId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 93,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 13,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 94,
                            DefensePokemonTypeId = 14,
                            OffensePokemonTypeId = 14,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 95,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 14,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 96,
                            DefensePokemonTypeId = 18,
                            OffensePokemonTypeId = 14,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 97,
                            DefensePokemonTypeId = 15,
                            OffensePokemonTypeId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 98,
                            DefensePokemonTypeId = 10,
                            OffensePokemonTypeId = 15,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 99,
                            DefensePokemonTypeId = 16,
                            OffensePokemonTypeId = 15,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 100,
                            DefensePokemonTypeId = 1,
                            OffensePokemonTypeId = 15,
                            Power = 0m
                        },
                        new
                        {
                            TypeEffectId = 101,
                            DefensePokemonTypeId = 15,
                            OffensePokemonTypeId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 102,
                            DefensePokemonTypeId = 10,
                            OffensePokemonTypeId = 16,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 103,
                            DefensePokemonTypeId = 16,
                            OffensePokemonTypeId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 104,
                            DefensePokemonTypeId = 18,
                            OffensePokemonTypeId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 105,
                            DefensePokemonTypeId = 3,
                            OffensePokemonTypeId = 16,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 106,
                            DefensePokemonTypeId = 18,
                            OffensePokemonTypeId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 107,
                            DefensePokemonTypeId = 12,
                            OffensePokemonTypeId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 108,
                            DefensePokemonTypeId = 11,
                            OffensePokemonTypeId = 17,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 109,
                            DefensePokemonTypeId = 8,
                            OffensePokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 110,
                            DefensePokemonTypeId = 2,
                            OffensePokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 111,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 112,
                            DefensePokemonTypeId = 4,
                            OffensePokemonTypeId = 17,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 113,
                            DefensePokemonTypeId = 16,
                            OffensePokemonTypeId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 114,
                            DefensePokemonTypeId = 14,
                            OffensePokemonTypeId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 115,
                            DefensePokemonTypeId = 3,
                            OffensePokemonTypeId = 18,
                            Power = 2m
                        },
                        new
                        {
                            TypeEffectId = 116,
                            DefensePokemonTypeId = 2,
                            OffensePokemonTypeId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 117,
                            DefensePokemonTypeId = 7,
                            OffensePokemonTypeId = 18,
                            Power = 0.5m
                        },
                        new
                        {
                            TypeEffectId = 118,
                            DefensePokemonTypeId = 17,
                            OffensePokemonTypeId = 18,
                            Power = 0.5m
                        });
                });

            modelBuilder.Entity("PokemonAPI.Models.TypeEffect", b =>
                {
                    b.HasOne("PokemonAPI.Models.PokemonType", "DefensePokemonType")
                        .WithMany("TypeDefense")
                        .HasForeignKey("DefensePokemonTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PokemonAPI.Models.PokemonType", "OffensePokemonType")
                        .WithMany("TypeOffense")
                        .HasForeignKey("OffensePokemonTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DefensePokemonType");

                    b.Navigation("OffensePokemonType");
                });

            modelBuilder.Entity("PokemonAPI.Models.PokemonType", b =>
                {
                    b.Navigation("TypeDefense");

                    b.Navigation("TypeOffense");
                });
#pragma warning restore 612, 618
        }
    }
}
