# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Aggr_578_Onix++"
      ACCEPT_EULA: "Y"
    ports: 
      - 1433:1433 
    volumes: 
        - ./db/data:/var/opt/mssql/data

  api:
    image: pokemonsapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - 5000:5000
      - 5001:5001
    depends_on: 
      - db
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./assets/csv:/assets/seeding
      - ~/.aspnet/https:/https:ro
